
// Code generated by ent, DO NOT EDIT.



	

package deckversion




import (
	"context"
	"errors"
	"fmt"
	"math"
	"strings"
	"sync"
	"time"
		"github.com/SAP/astonish/ent/personal/predicate"
				"github.com/google/uuid"
			"github.com/google/uuid"
	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/schema/field"
			"database/sql/driver"
			"entgo.io/ent/dialect/sql"
			"entgo.io/ent/dialect/sql/sqlgraph"
			"entgo.io/ent/dialect/sql/sqljson"
			"entgo.io/ent/schema/field"

)


const (
	// Label holds the string label denoting the deckversion type in the database.
	Label = "deck_version"
		// FieldID holds the string denoting the id field in the database.
		FieldID = "id"
		// FieldDeckSlug holds the string denoting the deck_slug field in the database.
		FieldDeckSlug = "deck_slug"
		// FieldVersion holds the string denoting the version field in the database.
		FieldVersion = "version"
		// FieldTitle holds the string denoting the title field in the database.
		FieldTitle = "title"
		// FieldSnapshot holds the string denoting the snapshot field in the database.
		FieldSnapshot = "snapshot"
		// FieldCreatedAt holds the string denoting the created_at field in the database.
		FieldCreatedAt = "created_at"
	// Table holds the table name of the deckversion in the database.
	Table = "deck_versions"

)



	
	// Columns holds all SQL columns for deckversion fields.
	var Columns = []string{
			FieldID,
				FieldDeckSlug,
				FieldVersion,
				FieldTitle,
				FieldSnapshot,
				FieldCreatedAt,
	}
	
	

	





	
// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}









	var (
				// DeckSlugValidator is a validator for the "deck_slug" field. It is called by the builders before save.
				DeckSlugValidator func (string) error
				// DefaultVersion holds the default value on creation for the "version" field.
				DefaultVersion int
				// TitleValidator is a validator for the "title" field. It is called by the builders before save.
				TitleValidator func (string) error
				// DefaultSnapshot holds the default value on creation for the "snapshot" field.
				DefaultSnapshot string
				// DefaultCreatedAt holds the default value on creation for the "created_at" field.
				DefaultCreatedAt func() time.Time
				// DefaultID holds the default value on creation for the "id" field.
				DefaultID func() uuid.UUID
	)






// OrderOption defines the ordering options for the DeckVersion queries.
type OrderOption func(*sql.Selector)

	
	
		// ByID orders the results by the id field.
		func ByID(opts ...sql.OrderTermOption) OrderOption {
			return sql.OrderByField(FieldID, opts...).ToFunc()
		}
	
			// ByDeckSlug orders the results by the deck_slug field.
			func ByDeckSlug(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldDeckSlug, opts...).ToFunc()
			}
			// ByVersion orders the results by the version field.
			func ByVersion(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldVersion, opts...).ToFunc()
			}
			// ByTitle orders the results by the title field.
			func ByTitle(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldTitle, opts...).ToFunc()
			}
			// BySnapshot orders the results by the snapshot field.
			func BySnapshot(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldSnapshot, opts...).ToFunc()
			}
			// ByCreatedAt orders the results by the created_at field.
			func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
				return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
			}







