// Code generated by ent, DO NOT EDIT.

package team

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/team/a2aagent"
	"github.com/google/uuid"
)

// A2aAgentCreate is the builder for creating a A2aAgent entity.
type A2aAgentCreate struct {
	config
	mutation *A2aAgentMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *A2aAgentCreate) SetName(v string) *A2aAgentCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *A2aAgentCreate) SetURL(v string) *A2aAgentCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetCredentialName sets the "credential_name" field.
func (_c *A2aAgentCreate) SetCredentialName(v string) *A2aAgentCreate {
	_c.mutation.SetCredentialName(v)
	return _c
}

// SetNillableCredentialName sets the "credential_name" field if the given value is not nil.
func (_c *A2aAgentCreate) SetNillableCredentialName(v *string) *A2aAgentCreate {
	if v != nil {
		_c.SetCredentialName(*v)
	}
	return _c
}

// SetAuthType sets the "auth_type" field.
func (_c *A2aAgentCreate) SetAuthType(v string) *A2aAgentCreate {
	_c.mutation.SetAuthType(v)
	return _c
}

// SetNillableAuthType sets the "auth_type" field if the given value is not nil.
func (_c *A2aAgentCreate) SetNillableAuthType(v *string) *A2aAgentCreate {
	if v != nil {
		_c.SetAuthType(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *A2aAgentCreate) SetEnabled(v bool) *A2aAgentCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *A2aAgentCreate) SetNillableEnabled(v *bool) *A2aAgentCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetHeaders sets the "headers" field.
func (_c *A2aAgentCreate) SetHeaders(v map[string]string) *A2aAgentCreate {
	_c.mutation.SetHeaders(v)
	return _c
}

// SetTimeout sets the "timeout" field.
func (_c *A2aAgentCreate) SetTimeout(v string) *A2aAgentCreate {
	_c.mutation.SetTimeout(v)
	return _c
}

// SetNillableTimeout sets the "timeout" field if the given value is not nil.
func (_c *A2aAgentCreate) SetNillableTimeout(v *string) *A2aAgentCreate {
	if v != nil {
		_c.SetTimeout(*v)
	}
	return _c
}

// SetCachedCard sets the "cached_card" field.
func (_c *A2aAgentCreate) SetCachedCard(v []uint8) *A2aAgentCreate {
	_c.mutation.SetCachedCard(v)
	return _c
}

// SetCachedSkills sets the "cached_skills" field.
func (_c *A2aAgentCreate) SetCachedSkills(v []interface{}) *A2aAgentCreate {
	_c.mutation.SetCachedSkills(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *A2aAgentCreate) SetCreatedBy(v uuid.UUID) *A2aAgentCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *A2aAgentCreate) SetCreatedAt(v time.Time) *A2aAgentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *A2aAgentCreate) SetNillableCreatedAt(v *time.Time) *A2aAgentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *A2aAgentCreate) SetUpdatedAt(v time.Time) *A2aAgentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *A2aAgentCreate) SetNillableUpdatedAt(v *time.Time) *A2aAgentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *A2aAgentCreate) SetID(v uuid.UUID) *A2aAgentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *A2aAgentCreate) SetNillableID(v *uuid.UUID) *A2aAgentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the A2aAgentMutation object of the builder.
func (_c *A2aAgentCreate) Mutation() *A2aAgentMutation {
	return _c.mutation
}

// Save creates the A2aAgent in the database.
func (_c *A2aAgentCreate) Save(ctx context.Context) (*A2aAgent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *A2aAgentCreate) SaveX(ctx context.Context) *A2aAgent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *A2aAgentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *A2aAgentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *A2aAgentCreate) defaults() {
	if _, ok := _c.mutation.AuthType(); !ok {
		v := a2aagent.DefaultAuthType
		_c.mutation.SetAuthType(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := a2aagent.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Headers(); !ok {
		v := a2aagent.DefaultHeaders
		_c.mutation.SetHeaders(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := a2aagent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := a2aagent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := a2aagent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *A2aAgentCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`team: missing required field "A2aAgent.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := a2aagent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`team: validator failed for field "A2aAgent.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`team: missing required field "A2aAgent.url"`)}
	}
	if v, ok := _c.mutation.URL(); ok {
		if err := a2aagent.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`team: validator failed for field "A2aAgent.url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthType(); !ok {
		return &ValidationError{Name: "auth_type", err: errors.New(`team: missing required field "A2aAgent.auth_type"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`team: missing required field "A2aAgent.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`team: missing required field "A2aAgent.created_by"`)}
	}
	switch _c.driver.Dialect() {
	case dialect.MySQL, dialect.SQLite:
		if _, ok := _c.mutation.CreatedAt(); !ok {
			return &ValidationError{Name: "created_at", err: errors.New(`team: missing required field "A2aAgent.created_at"`)}
		}
	}
	switch _c.driver.Dialect() {
	case dialect.MySQL, dialect.SQLite:
		if _, ok := _c.mutation.UpdatedAt(); !ok {
			return &ValidationError{Name: "updated_at", err: errors.New(`team: missing required field "A2aAgent.updated_at"`)}
		}
	}
	return nil
}

func (_c *A2aAgentCreate) sqlSave(ctx context.Context) (*A2aAgent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *A2aAgentCreate) createSpec() (*A2aAgent, *sqlgraph.CreateSpec) {
	var (
		_node = &A2aAgent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(a2aagent.Table, sqlgraph.NewFieldSpec(a2aagent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(a2aagent.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(a2aagent.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.CredentialName(); ok {
		_spec.SetField(a2aagent.FieldCredentialName, field.TypeString, value)
		_node.CredentialName = &value
	}
	if value, ok := _c.mutation.AuthType(); ok {
		_spec.SetField(a2aagent.FieldAuthType, field.TypeString, value)
		_node.AuthType = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(a2aagent.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Headers(); ok {
		_spec.SetField(a2aagent.FieldHeaders, field.TypeJSON, value)
		_node.Headers = value
	}
	if value, ok := _c.mutation.Timeout(); ok {
		_spec.SetField(a2aagent.FieldTimeout, field.TypeString, value)
		_node.Timeout = &value
	}
	if value, ok := _c.mutation.CachedCard(); ok {
		_spec.SetField(a2aagent.FieldCachedCard, field.TypeJSON, value)
		_node.CachedCard = value
	}
	if value, ok := _c.mutation.CachedSkills(); ok {
		_spec.SetField(a2aagent.FieldCachedSkills, field.TypeJSON, value)
		_node.CachedSkills = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(a2aagent.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(a2aagent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(a2aagent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// A2aAgentCreateBulk is the builder for creating many A2aAgent entities in bulk.
type A2aAgentCreateBulk struct {
	config
	err      error
	builders []*A2aAgentCreate
}

// Save creates the A2aAgent entities in the database.
func (_c *A2aAgentCreateBulk) Save(ctx context.Context) ([]*A2aAgent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*A2aAgent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*A2aAgentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *A2aAgentCreateBulk) SaveX(ctx context.Context) []*A2aAgent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *A2aAgentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *A2aAgentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
