// Code generated by ent, DO NOT EDIT.

package team

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/team/a2aagent"
	"github.com/SAP/astonish/ent/team/predicate"
)

// A2aAgentDelete is the builder for deleting a A2aAgent entity.
type A2aAgentDelete struct {
	config
	hooks    []Hook
	mutation *A2aAgentMutation
}

// Where appends a list predicates to the A2aAgentDelete builder.
func (_d *A2aAgentDelete) Where(ps ...predicate.A2aAgent) *A2aAgentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *A2aAgentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *A2aAgentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *A2aAgentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(a2aagent.Table, sqlgraph.NewFieldSpec(a2aagent.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// A2aAgentDeleteOne is the builder for deleting a single A2aAgent entity.
type A2aAgentDeleteOne struct {
	_d *A2aAgentDelete
}

// Where appends a list predicates to the A2aAgentDelete builder.
func (_d *A2aAgentDeleteOne) Where(ps ...predicate.A2aAgent) *A2aAgentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *A2aAgentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{a2aagent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *A2aAgentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
