// Code generated by ent, DO NOT EDIT.

package team

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SAP/astonish/ent/team/cachediagnostic"
	"github.com/SAP/astonish/ent/team/session"
)

// CacheDiagnostic is the model entity for the CacheDiagnostic schema.
type CacheDiagnostic struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// InvocationID holds the value of the "invocation_id" field.
	InvocationID string `json:"invocation_id,omitempty"`
	// Call holds the value of the "call" field.
	Call int `json:"call,omitempty"`
	// Data holds the value of the "data" field.
	Data []byte `json:"data,omitempty"`
	// Round holds the value of the "round" field.
	Round int `json:"round,omitempty"`
	// CacheStablePath holds the value of the "cache_stable_path" field.
	CacheStablePath bool `json:"cache_stable_path,omitempty"`
	// SystemHash holds the value of the "system_hash" field.
	SystemHash string `json:"system_hash,omitempty"`
	// SystemChanged holds the value of the "system_changed" field.
	SystemChanged bool `json:"system_changed,omitempty"`
	// SystemChangedSession holds the value of the "system_changed_session" field.
	SystemChangedSession bool `json:"system_changed_session,omitempty"`
	// ToolHash holds the value of the "tool_hash" field.
	ToolHash string `json:"tool_hash,omitempty"`
	// ToolCount holds the value of the "tool_count" field.
	ToolCount int `json:"tool_count,omitempty"`
	// ToolsChanged holds the value of the "tools_changed" field.
	ToolsChanged bool `json:"tools_changed,omitempty"`
	// ToolsChangedSession holds the value of the "tools_changed_session" field.
	ToolsChangedSession bool `json:"tools_changed_session,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CacheDiagnosticQuery when eager-loading is set.
	Edges        CacheDiagnosticEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CacheDiagnosticEdges holds the relations/edges for other nodes in the graph.
type CacheDiagnosticEdges struct {
	// Session holds the value of the session edge.
	Session *Session `json:"session,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SessionOrErr returns the Session value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CacheDiagnosticEdges) SessionOrErr() (*Session, error) {
	if e.Session != nil {
		return e.Session, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: session.Label}
	}
	return nil, &NotLoadedError{edge: "session"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CacheDiagnostic) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cachediagnostic.FieldData:
			values[i] = new([]byte)
		case cachediagnostic.FieldCacheStablePath, cachediagnostic.FieldSystemChanged, cachediagnostic.FieldSystemChangedSession, cachediagnostic.FieldToolsChanged, cachediagnostic.FieldToolsChangedSession:
			values[i] = new(sql.NullBool)
		case cachediagnostic.FieldID, cachediagnostic.FieldCall, cachediagnostic.FieldRound, cachediagnostic.FieldToolCount:
			values[i] = new(sql.NullInt64)
		case cachediagnostic.FieldSessionID, cachediagnostic.FieldInvocationID, cachediagnostic.FieldSystemHash, cachediagnostic.FieldToolHash:
			values[i] = new(sql.NullString)
		case cachediagnostic.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CacheDiagnostic fields.
func (_m *CacheDiagnostic) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cachediagnostic.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case cachediagnostic.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case cachediagnostic.FieldInvocationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invocation_id", values[i])
			} else if value.Valid {
				_m.InvocationID = value.String
			}
		case cachediagnostic.FieldCall:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field call", values[i])
			} else if value.Valid {
				_m.Call = int(value.Int64)
			}
		case cachediagnostic.FieldData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value != nil {
				_m.Data = *value
			}
		case cachediagnostic.FieldRound:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field round", values[i])
			} else if value.Valid {
				_m.Round = int(value.Int64)
			}
		case cachediagnostic.FieldCacheStablePath:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field cache_stable_path", values[i])
			} else if value.Valid {
				_m.CacheStablePath = value.Bool
			}
		case cachediagnostic.FieldSystemHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field system_hash", values[i])
			} else if value.Valid {
				_m.SystemHash = value.String
			}
		case cachediagnostic.FieldSystemChanged:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field system_changed", values[i])
			} else if value.Valid {
				_m.SystemChanged = value.Bool
			}
		case cachediagnostic.FieldSystemChangedSession:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field system_changed_session", values[i])
			} else if value.Valid {
				_m.SystemChangedSession = value.Bool
			}
		case cachediagnostic.FieldToolHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tool_hash", values[i])
			} else if value.Valid {
				_m.ToolHash = value.String
			}
		case cachediagnostic.FieldToolCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tool_count", values[i])
			} else if value.Valid {
				_m.ToolCount = int(value.Int64)
			}
		case cachediagnostic.FieldToolsChanged:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field tools_changed", values[i])
			} else if value.Valid {
				_m.ToolsChanged = value.Bool
			}
		case cachediagnostic.FieldToolsChangedSession:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field tools_changed_session", values[i])
			} else if value.Valid {
				_m.ToolsChangedSession = value.Bool
			}
		case cachediagnostic.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CacheDiagnostic.
// This includes values selected through modifiers, order, etc.
func (_m *CacheDiagnostic) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySession queries the "session" edge of the CacheDiagnostic entity.
func (_m *CacheDiagnostic) QuerySession() *SessionQuery {
	return NewCacheDiagnosticClient(_m.config).QuerySession(_m)
}

// Update returns a builder for updating this CacheDiagnostic.
// Note that you need to call CacheDiagnostic.Unwrap() before calling this method if this CacheDiagnostic
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CacheDiagnostic) Update() *CacheDiagnosticUpdateOne {
	return NewCacheDiagnosticClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CacheDiagnostic entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CacheDiagnostic) Unwrap() *CacheDiagnostic {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("team: CacheDiagnostic is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CacheDiagnostic) String() string {
	var builder strings.Builder
	builder.WriteString("CacheDiagnostic(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("invocation_id=")
	builder.WriteString(_m.InvocationID)
	builder.WriteString(", ")
	builder.WriteString("call=")
	builder.WriteString(fmt.Sprintf("%v", _m.Call))
	builder.WriteString(", ")
	builder.WriteString("data=")
	builder.WriteString(fmt.Sprintf("%v", _m.Data))
	builder.WriteString(", ")
	builder.WriteString("round=")
	builder.WriteString(fmt.Sprintf("%v", _m.Round))
	builder.WriteString(", ")
	builder.WriteString("cache_stable_path=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheStablePath))
	builder.WriteString(", ")
	builder.WriteString("system_hash=")
	builder.WriteString(_m.SystemHash)
	builder.WriteString(", ")
	builder.WriteString("system_changed=")
	builder.WriteString(fmt.Sprintf("%v", _m.SystemChanged))
	builder.WriteString(", ")
	builder.WriteString("system_changed_session=")
	builder.WriteString(fmt.Sprintf("%v", _m.SystemChangedSession))
	builder.WriteString(", ")
	builder.WriteString("tool_hash=")
	builder.WriteString(_m.ToolHash)
	builder.WriteString(", ")
	builder.WriteString("tool_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ToolCount))
	builder.WriteString(", ")
	builder.WriteString("tools_changed=")
	builder.WriteString(fmt.Sprintf("%v", _m.ToolsChanged))
	builder.WriteString(", ")
	builder.WriteString("tools_changed_session=")
	builder.WriteString(fmt.Sprintf("%v", _m.ToolsChangedSession))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CacheDiagnostics is a parsable slice of CacheDiagnostic.
type CacheDiagnostics []*CacheDiagnostic
