// Code generated by ent, DO NOT EDIT.

package team

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/team/cachediagnostic"
	"github.com/SAP/astonish/ent/team/predicate"
)

// CacheDiagnosticDelete is the builder for deleting a CacheDiagnostic entity.
type CacheDiagnosticDelete struct {
	config
	hooks    []Hook
	mutation *CacheDiagnosticMutation
}

// Where appends a list predicates to the CacheDiagnosticDelete builder.
func (_d *CacheDiagnosticDelete) Where(ps ...predicate.CacheDiagnostic) *CacheDiagnosticDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CacheDiagnosticDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CacheDiagnosticDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CacheDiagnosticDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(cachediagnostic.Table, sqlgraph.NewFieldSpec(cachediagnostic.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CacheDiagnosticDeleteOne is the builder for deleting a single CacheDiagnostic entity.
type CacheDiagnosticDeleteOne struct {
	_d *CacheDiagnosticDelete
}

// Where appends a list predicates to the CacheDiagnosticDelete builder.
func (_d *CacheDiagnosticDeleteOne) Where(ps ...predicate.CacheDiagnostic) *CacheDiagnosticDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CacheDiagnosticDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cachediagnostic.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CacheDiagnosticDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
