// Code generated by ent, DO NOT EDIT.

package team

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/team/cachediagnostic"
	"github.com/SAP/astonish/ent/team/predicate"
	"github.com/SAP/astonish/ent/team/session"
)

// CacheDiagnosticUpdate is the builder for updating CacheDiagnostic entities.
type CacheDiagnosticUpdate struct {
	config
	hooks    []Hook
	mutation *CacheDiagnosticMutation
}

// Where appends a list predicates to the CacheDiagnosticUpdate builder.
func (_u *CacheDiagnosticUpdate) Where(ps ...predicate.CacheDiagnostic) *CacheDiagnosticUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *CacheDiagnosticUpdate) SetSessionID(v string) *CacheDiagnosticUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *CacheDiagnosticUpdate) SetNillableSessionID(v *string) *CacheDiagnosticUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetInvocationID sets the "invocation_id" field.
func (_u *CacheDiagnosticUpdate) SetInvocationID(v string) *CacheDiagnosticUpdate {
	_u.mutation.SetInvocationID(v)
	return _u
}

// SetNillableInvocationID sets the "invocation_id" field if the given value is not nil.
func (_u *CacheDiagnosticUpdate) SetNillableInvocationID(v *string) *CacheDiagnosticUpdate {
	if v != nil {
		_u.SetInvocationID(*v)
	}
	return _u
}

// SetCall sets the "call" field.
func (_u *CacheDiagnosticUpdate) SetCall(v int) *CacheDiagnosticUpdate {
	_u.mutation.ResetCall()
	_u.mutation.SetCall(v)
	return _u
}

// SetNillableCall sets the "call" field if the given value is not nil.
func (_u *CacheDiagnosticUpdate) SetNillableCall(v *int) *CacheDiagnosticUpdate {
	if v != nil {
		_u.SetCall(*v)
	}
	return _u
}

// AddCall adds value to the "call" field.
func (_u *CacheDiagnosticUpdate) AddCall(v int) *CacheDiagnosticUpdate {
	_u.mutation.AddCall(v)
	return _u
}

// SetData sets the "data" field.
func (_u *CacheDiagnosticUpdate) SetData(v []byte) *CacheDiagnosticUpdate {
	_u.mutation.SetData(v)
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *CacheDiagnosticUpdate) ClearData() *CacheDiagnosticUpdate {
	_u.mutation.ClearData()
	return _u
}

// SetRound sets the "round" field.
func (_u *CacheDiagnosticUpdate) SetRound(v int) *CacheDiagnosticUpdate {
	_u.mutation.ResetRound()
	_u.mutation.SetRound(v)
	return _u
}

// SetNillableRound sets the "round" field if the given value is not nil.
func (_u *CacheDiagnosticUpdate) SetNillableRound(v *int) *CacheDiagnosticUpdate {
	if v != nil {
		_u.SetRound(*v)
	}
	return _u
}

// AddRound adds value to the "round" field.
func (_u *CacheDiagnosticUpdate) AddRound(v int) *CacheDiagnosticUpdate {
	_u.mutation.AddRound(v)
	return _u
}

// SetCacheStablePath sets the "cache_stable_path" field.
func (_u *CacheDiagnosticUpdate) SetCacheStablePath(v bool) *CacheDiagnosticUpdate {
	_u.mutation.SetCacheStablePath(v)
	return _u
}

// SetNillableCacheStablePath sets the "cache_stable_path" field if the given value is not nil.
func (_u *CacheDiagnosticUpdate) SetNillableCacheStablePath(v *bool) *CacheDiagnosticUpdate {
	if v != nil {
		_u.SetCacheStablePath(*v)
	}
	return _u
}

// SetSystemHash sets the "system_hash" field.
func (_u *CacheDiagnosticUpdate) SetSystemHash(v string) *CacheDiagnosticUpdate {
	_u.mutation.SetSystemHash(v)
	return _u
}

// SetNillableSystemHash sets the "system_hash" field if the given value is not nil.
func (_u *CacheDiagnosticUpdate) SetNillableSystemHash(v *string) *CacheDiagnosticUpdate {
	if v != nil {
		_u.SetSystemHash(*v)
	}
	return _u
}

// SetSystemChanged sets the "system_changed" field.
func (_u *CacheDiagnosticUpdate) SetSystemChanged(v bool) *CacheDiagnosticUpdate {
	_u.mutation.SetSystemChanged(v)
	return _u
}

// SetNillableSystemChanged sets the "system_changed" field if the given value is not nil.
func (_u *CacheDiagnosticUpdate) SetNillableSystemChanged(v *bool) *CacheDiagnosticUpdate {
	if v != nil {
		_u.SetSystemChanged(*v)
	}
	return _u
}

// SetSystemChangedSession sets the "system_changed_session" field.
func (_u *CacheDiagnosticUpdate) SetSystemChangedSession(v bool) *CacheDiagnosticUpdate {
	_u.mutation.SetSystemChangedSession(v)
	return _u
}

// SetNillableSystemChangedSession sets the "system_changed_session" field if the given value is not nil.
func (_u *CacheDiagnosticUpdate) SetNillableSystemChangedSession(v *bool) *CacheDiagnosticUpdate {
	if v != nil {
		_u.SetSystemChangedSession(*v)
	}
	return _u
}

// SetToolHash sets the "tool_hash" field.
func (_u *CacheDiagnosticUpdate) SetToolHash(v string) *CacheDiagnosticUpdate {
	_u.mutation.SetToolHash(v)
	return _u
}

// SetNillableToolHash sets the "tool_hash" field if the given value is not nil.
func (_u *CacheDiagnosticUpdate) SetNillableToolHash(v *string) *CacheDiagnosticUpdate {
	if v != nil {
		_u.SetToolHash(*v)
	}
	return _u
}

// SetToolCount sets the "tool_count" field.
func (_u *CacheDiagnosticUpdate) SetToolCount(v int) *CacheDiagnosticUpdate {
	_u.mutation.ResetToolCount()
	_u.mutation.SetToolCount(v)
	return _u
}

// SetNillableToolCount sets the "tool_count" field if the given value is not nil.
func (_u *CacheDiagnosticUpdate) SetNillableToolCount(v *int) *CacheDiagnosticUpdate {
	if v != nil {
		_u.SetToolCount(*v)
	}
	return _u
}

// AddToolCount adds value to the "tool_count" field.
func (_u *CacheDiagnosticUpdate) AddToolCount(v int) *CacheDiagnosticUpdate {
	_u.mutation.AddToolCount(v)
	return _u
}

// SetToolsChanged sets the "tools_changed" field.
func (_u *CacheDiagnosticUpdate) SetToolsChanged(v bool) *CacheDiagnosticUpdate {
	_u.mutation.SetToolsChanged(v)
	return _u
}

// SetNillableToolsChanged sets the "tools_changed" field if the given value is not nil.
func (_u *CacheDiagnosticUpdate) SetNillableToolsChanged(v *bool) *CacheDiagnosticUpdate {
	if v != nil {
		_u.SetToolsChanged(*v)
	}
	return _u
}

// SetToolsChangedSession sets the "tools_changed_session" field.
func (_u *CacheDiagnosticUpdate) SetToolsChangedSession(v bool) *CacheDiagnosticUpdate {
	_u.mutation.SetToolsChangedSession(v)
	return _u
}

// SetNillableToolsChangedSession sets the "tools_changed_session" field if the given value is not nil.
func (_u *CacheDiagnosticUpdate) SetNillableToolsChangedSession(v *bool) *CacheDiagnosticUpdate {
	if v != nil {
		_u.SetToolsChangedSession(*v)
	}
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *CacheDiagnosticUpdate) SetSession(v *Session) *CacheDiagnosticUpdate {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the CacheDiagnosticMutation object of the builder.
func (_u *CacheDiagnosticUpdate) Mutation() *CacheDiagnosticMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *CacheDiagnosticUpdate) ClearSession() *CacheDiagnosticUpdate {
	_u.mutation.ClearSession()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CacheDiagnosticUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CacheDiagnosticUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CacheDiagnosticUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CacheDiagnosticUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CacheDiagnosticUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := cachediagnostic.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`team: validator failed for field "CacheDiagnostic.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SystemHash(); ok {
		if err := cachediagnostic.SystemHashValidator(v); err != nil {
			return &ValidationError{Name: "system_hash", err: fmt.Errorf(`team: validator failed for field "CacheDiagnostic.system_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ToolHash(); ok {
		if err := cachediagnostic.ToolHashValidator(v); err != nil {
			return &ValidationError{Name: "tool_hash", err: fmt.Errorf(`team: validator failed for field "CacheDiagnostic.tool_hash": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`team: clearing a required unique edge "CacheDiagnostic.session"`)
	}
	return nil
}

func (_u *CacheDiagnosticUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cachediagnostic.Table, cachediagnostic.Columns, sqlgraph.NewFieldSpec(cachediagnostic.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InvocationID(); ok {
		_spec.SetField(cachediagnostic.FieldInvocationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Call(); ok {
		_spec.SetField(cachediagnostic.FieldCall, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCall(); ok {
		_spec.AddField(cachediagnostic.FieldCall, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(cachediagnostic.FieldData, field.TypeBytes, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(cachediagnostic.FieldData, field.TypeBytes)
	}
	if value, ok := _u.mutation.Round(); ok {
		_spec.SetField(cachediagnostic.FieldRound, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRound(); ok {
		_spec.AddField(cachediagnostic.FieldRound, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CacheStablePath(); ok {
		_spec.SetField(cachediagnostic.FieldCacheStablePath, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SystemHash(); ok {
		_spec.SetField(cachediagnostic.FieldSystemHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.SystemChanged(); ok {
		_spec.SetField(cachediagnostic.FieldSystemChanged, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SystemChangedSession(); ok {
		_spec.SetField(cachediagnostic.FieldSystemChangedSession, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ToolHash(); ok {
		_spec.SetField(cachediagnostic.FieldToolHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToolCount(); ok {
		_spec.SetField(cachediagnostic.FieldToolCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedToolCount(); ok {
		_spec.AddField(cachediagnostic.FieldToolCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ToolsChanged(); ok {
		_spec.SetField(cachediagnostic.FieldToolsChanged, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ToolsChangedSession(); ok {
		_spec.SetField(cachediagnostic.FieldToolsChangedSession, field.TypeBool, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cachediagnostic.SessionTable,
			Columns: []string{cachediagnostic.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cachediagnostic.SessionTable,
			Columns: []string{cachediagnostic.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cachediagnostic.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CacheDiagnosticUpdateOne is the builder for updating a single CacheDiagnostic entity.
type CacheDiagnosticUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CacheDiagnosticMutation
}

// SetSessionID sets the "session_id" field.
func (_u *CacheDiagnosticUpdateOne) SetSessionID(v string) *CacheDiagnosticUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *CacheDiagnosticUpdateOne) SetNillableSessionID(v *string) *CacheDiagnosticUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetInvocationID sets the "invocation_id" field.
func (_u *CacheDiagnosticUpdateOne) SetInvocationID(v string) *CacheDiagnosticUpdateOne {
	_u.mutation.SetInvocationID(v)
	return _u
}

// SetNillableInvocationID sets the "invocation_id" field if the given value is not nil.
func (_u *CacheDiagnosticUpdateOne) SetNillableInvocationID(v *string) *CacheDiagnosticUpdateOne {
	if v != nil {
		_u.SetInvocationID(*v)
	}
	return _u
}

// SetCall sets the "call" field.
func (_u *CacheDiagnosticUpdateOne) SetCall(v int) *CacheDiagnosticUpdateOne {
	_u.mutation.ResetCall()
	_u.mutation.SetCall(v)
	return _u
}

// SetNillableCall sets the "call" field if the given value is not nil.
func (_u *CacheDiagnosticUpdateOne) SetNillableCall(v *int) *CacheDiagnosticUpdateOne {
	if v != nil {
		_u.SetCall(*v)
	}
	return _u
}

// AddCall adds value to the "call" field.
func (_u *CacheDiagnosticUpdateOne) AddCall(v int) *CacheDiagnosticUpdateOne {
	_u.mutation.AddCall(v)
	return _u
}

// SetData sets the "data" field.
func (_u *CacheDiagnosticUpdateOne) SetData(v []byte) *CacheDiagnosticUpdateOne {
	_u.mutation.SetData(v)
	return _u
}

// ClearData clears the value of the "data" field.
func (_u *CacheDiagnosticUpdateOne) ClearData() *CacheDiagnosticUpdateOne {
	_u.mutation.ClearData()
	return _u
}

// SetRound sets the "round" field.
func (_u *CacheDiagnosticUpdateOne) SetRound(v int) *CacheDiagnosticUpdateOne {
	_u.mutation.ResetRound()
	_u.mutation.SetRound(v)
	return _u
}

// SetNillableRound sets the "round" field if the given value is not nil.
func (_u *CacheDiagnosticUpdateOne) SetNillableRound(v *int) *CacheDiagnosticUpdateOne {
	if v != nil {
		_u.SetRound(*v)
	}
	return _u
}

// AddRound adds value to the "round" field.
func (_u *CacheDiagnosticUpdateOne) AddRound(v int) *CacheDiagnosticUpdateOne {
	_u.mutation.AddRound(v)
	return _u
}

// SetCacheStablePath sets the "cache_stable_path" field.
func (_u *CacheDiagnosticUpdateOne) SetCacheStablePath(v bool) *CacheDiagnosticUpdateOne {
	_u.mutation.SetCacheStablePath(v)
	return _u
}

// SetNillableCacheStablePath sets the "cache_stable_path" field if the given value is not nil.
func (_u *CacheDiagnosticUpdateOne) SetNillableCacheStablePath(v *bool) *CacheDiagnosticUpdateOne {
	if v != nil {
		_u.SetCacheStablePath(*v)
	}
	return _u
}

// SetSystemHash sets the "system_hash" field.
func (_u *CacheDiagnosticUpdateOne) SetSystemHash(v string) *CacheDiagnosticUpdateOne {
	_u.mutation.SetSystemHash(v)
	return _u
}

// SetNillableSystemHash sets the "system_hash" field if the given value is not nil.
func (_u *CacheDiagnosticUpdateOne) SetNillableSystemHash(v *string) *CacheDiagnosticUpdateOne {
	if v != nil {
		_u.SetSystemHash(*v)
	}
	return _u
}

// SetSystemChanged sets the "system_changed" field.
func (_u *CacheDiagnosticUpdateOne) SetSystemChanged(v bool) *CacheDiagnosticUpdateOne {
	_u.mutation.SetSystemChanged(v)
	return _u
}

// SetNillableSystemChanged sets the "system_changed" field if the given value is not nil.
func (_u *CacheDiagnosticUpdateOne) SetNillableSystemChanged(v *bool) *CacheDiagnosticUpdateOne {
	if v != nil {
		_u.SetSystemChanged(*v)
	}
	return _u
}

// SetSystemChangedSession sets the "system_changed_session" field.
func (_u *CacheDiagnosticUpdateOne) SetSystemChangedSession(v bool) *CacheDiagnosticUpdateOne {
	_u.mutation.SetSystemChangedSession(v)
	return _u
}

// SetNillableSystemChangedSession sets the "system_changed_session" field if the given value is not nil.
func (_u *CacheDiagnosticUpdateOne) SetNillableSystemChangedSession(v *bool) *CacheDiagnosticUpdateOne {
	if v != nil {
		_u.SetSystemChangedSession(*v)
	}
	return _u
}

// SetToolHash sets the "tool_hash" field.
func (_u *CacheDiagnosticUpdateOne) SetToolHash(v string) *CacheDiagnosticUpdateOne {
	_u.mutation.SetToolHash(v)
	return _u
}

// SetNillableToolHash sets the "tool_hash" field if the given value is not nil.
func (_u *CacheDiagnosticUpdateOne) SetNillableToolHash(v *string) *CacheDiagnosticUpdateOne {
	if v != nil {
		_u.SetToolHash(*v)
	}
	return _u
}

// SetToolCount sets the "tool_count" field.
func (_u *CacheDiagnosticUpdateOne) SetToolCount(v int) *CacheDiagnosticUpdateOne {
	_u.mutation.ResetToolCount()
	_u.mutation.SetToolCount(v)
	return _u
}

// SetNillableToolCount sets the "tool_count" field if the given value is not nil.
func (_u *CacheDiagnosticUpdateOne) SetNillableToolCount(v *int) *CacheDiagnosticUpdateOne {
	if v != nil {
		_u.SetToolCount(*v)
	}
	return _u
}

// AddToolCount adds value to the "tool_count" field.
func (_u *CacheDiagnosticUpdateOne) AddToolCount(v int) *CacheDiagnosticUpdateOne {
	_u.mutation.AddToolCount(v)
	return _u
}

// SetToolsChanged sets the "tools_changed" field.
func (_u *CacheDiagnosticUpdateOne) SetToolsChanged(v bool) *CacheDiagnosticUpdateOne {
	_u.mutation.SetToolsChanged(v)
	return _u
}

// SetNillableToolsChanged sets the "tools_changed" field if the given value is not nil.
func (_u *CacheDiagnosticUpdateOne) SetNillableToolsChanged(v *bool) *CacheDiagnosticUpdateOne {
	if v != nil {
		_u.SetToolsChanged(*v)
	}
	return _u
}

// SetToolsChangedSession sets the "tools_changed_session" field.
func (_u *CacheDiagnosticUpdateOne) SetToolsChangedSession(v bool) *CacheDiagnosticUpdateOne {
	_u.mutation.SetToolsChangedSession(v)
	return _u
}

// SetNillableToolsChangedSession sets the "tools_changed_session" field if the given value is not nil.
func (_u *CacheDiagnosticUpdateOne) SetNillableToolsChangedSession(v *bool) *CacheDiagnosticUpdateOne {
	if v != nil {
		_u.SetToolsChangedSession(*v)
	}
	return _u
}

// SetSession sets the "session" edge to the Session entity.
func (_u *CacheDiagnosticUpdateOne) SetSession(v *Session) *CacheDiagnosticUpdateOne {
	return _u.SetSessionID(v.ID)
}

// Mutation returns the CacheDiagnosticMutation object of the builder.
func (_u *CacheDiagnosticUpdateOne) Mutation() *CacheDiagnosticMutation {
	return _u.mutation
}

// ClearSession clears the "session" edge to the Session entity.
func (_u *CacheDiagnosticUpdateOne) ClearSession() *CacheDiagnosticUpdateOne {
	_u.mutation.ClearSession()
	return _u
}

// Where appends a list predicates to the CacheDiagnosticUpdate builder.
func (_u *CacheDiagnosticUpdateOne) Where(ps ...predicate.CacheDiagnostic) *CacheDiagnosticUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CacheDiagnosticUpdateOne) Select(field string, fields ...string) *CacheDiagnosticUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CacheDiagnostic entity.
func (_u *CacheDiagnosticUpdateOne) Save(ctx context.Context) (*CacheDiagnostic, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CacheDiagnosticUpdateOne) SaveX(ctx context.Context) *CacheDiagnostic {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CacheDiagnosticUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CacheDiagnosticUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CacheDiagnosticUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := cachediagnostic.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`team: validator failed for field "CacheDiagnostic.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SystemHash(); ok {
		if err := cachediagnostic.SystemHashValidator(v); err != nil {
			return &ValidationError{Name: "system_hash", err: fmt.Errorf(`team: validator failed for field "CacheDiagnostic.system_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ToolHash(); ok {
		if err := cachediagnostic.ToolHashValidator(v); err != nil {
			return &ValidationError{Name: "tool_hash", err: fmt.Errorf(`team: validator failed for field "CacheDiagnostic.tool_hash": %w`, err)}
		}
	}
	if _u.mutation.SessionCleared() && len(_u.mutation.SessionIDs()) > 0 {
		return errors.New(`team: clearing a required unique edge "CacheDiagnostic.session"`)
	}
	return nil
}

func (_u *CacheDiagnosticUpdateOne) sqlSave(ctx context.Context) (_node *CacheDiagnostic, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(cachediagnostic.Table, cachediagnostic.Columns, sqlgraph.NewFieldSpec(cachediagnostic.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`team: missing "CacheDiagnostic.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cachediagnostic.FieldID)
		for _, f := range fields {
			if !cachediagnostic.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("team: invalid field %q for query", f)}
			}
			if f != cachediagnostic.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InvocationID(); ok {
		_spec.SetField(cachediagnostic.FieldInvocationID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Call(); ok {
		_spec.SetField(cachediagnostic.FieldCall, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCall(); ok {
		_spec.AddField(cachediagnostic.FieldCall, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Data(); ok {
		_spec.SetField(cachediagnostic.FieldData, field.TypeBytes, value)
	}
	if _u.mutation.DataCleared() {
		_spec.ClearField(cachediagnostic.FieldData, field.TypeBytes)
	}
	if value, ok := _u.mutation.Round(); ok {
		_spec.SetField(cachediagnostic.FieldRound, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRound(); ok {
		_spec.AddField(cachediagnostic.FieldRound, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CacheStablePath(); ok {
		_spec.SetField(cachediagnostic.FieldCacheStablePath, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SystemHash(); ok {
		_spec.SetField(cachediagnostic.FieldSystemHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.SystemChanged(); ok {
		_spec.SetField(cachediagnostic.FieldSystemChanged, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SystemChangedSession(); ok {
		_spec.SetField(cachediagnostic.FieldSystemChangedSession, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ToolHash(); ok {
		_spec.SetField(cachediagnostic.FieldToolHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ToolCount(); ok {
		_spec.SetField(cachediagnostic.FieldToolCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedToolCount(); ok {
		_spec.AddField(cachediagnostic.FieldToolCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ToolsChanged(); ok {
		_spec.SetField(cachediagnostic.FieldToolsChanged, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ToolsChangedSession(); ok {
		_spec.SetField(cachediagnostic.FieldToolsChangedSession, field.TypeBool, value)
	}
	if _u.mutation.SessionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cachediagnostic.SessionTable,
			Columns: []string{cachediagnostic.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SessionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cachediagnostic.SessionTable,
			Columns: []string{cachediagnostic.SessionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CacheDiagnostic{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cachediagnostic.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
