package api

import (
	"testing"
	"time"

	"google.golang.org/adk/model"
	"google.golang.org/adk/session"
	"google.golang.org/genai"
)

// These tests cover the astonish-report fence pipeline introduced to make
// "is this artifact a report?" an explicit contract:
//
//   ```astonish-report
//   path: <abs path of a same-turn write_file/edit_file artifact>
//   title: <optional human-readable title>
//   ```
//
// The fence is a *signal*. The artifact's content is still produced by
// write_file / edit_file; the fence only flips ArtifactInfo.IsReport so the
// frontend embeds the artifact inline as EmbeddedFileViewer instead of the
// compact ArtifactCard. These tests pin the parser, the path-validation
// gate, the dedup contract, the persistence round-trip, and the join
// projection onto ArtifactInfo.

// TestParseReportMarkerFrontmatter_HappyPath: the canonical case — a fence
// body with both required path and optional title. Parser must accept it
// and return both fields verbatim.
func TestParseReportMarkerFrontmatter_HappyPath(t *testing.T) {
	body := "path: /tmp/report.md\ntitle: Q4 Revenue Analysis"
	info, ok := parseReportMarkerFrontmatter(body)
	if !ok {
		t.Fatal("expected ok=true for fence with path+title")
	}
	if info.Path != "/tmp/report.md" {
		t.Errorf("path = %q, want /tmp/report.md", info.Path)
	}
	if info.Title != "Q4 Revenue Analysis" {
		t.Errorf("title = %q, want Q4 Revenue Analysis", info.Title)
	}
}

// TestParseReportMarkerFrontmatter_MissingPath: path is the only required
// field. A fence with title but no path must be rejected — the marker is
// useless without a target artifact to attach to.
func TestParseReportMarkerFrontmatter_MissingPath(t *testing.T) {
	body := "title: Just a title\nsummary: only metadata"
	if _, ok := parseReportMarkerFrontmatter(body); ok {
		t.Fatal("expected ok=false when path is missing")
	}
}

// TestParseReportMarkerFrontmatter_UnknownKeysIgnored: the parser is
// forward-compatible. Future fields (mermaid_hint, export_formats, etc.)
// must be tolerated silently so older binaries don't error on newer
// agent output.
func TestParseReportMarkerFrontmatter_UnknownKeysIgnored(t *testing.T) {
	body := "path: /tmp/x.md\ntitle: T\nfuture_field: whatever\nanother: 42"
	info, ok := parseReportMarkerFrontmatter(body)
	if !ok {
		t.Fatal("expected ok=true; unknown keys must not fail parsing")
	}
	if info.Path != "/tmp/x.md" || info.Title != "T" {
		t.Errorf("parsed = %+v, want path=/tmp/x.md title=T", info)
	}
}

// TestParseReportMarkerFrontmatter_QuotesAndComments: surrounding quotes
// (single or double) and YAML-style comment lines are tolerated. This
// keeps the parser robust against minor LLM quoting habits.
func TestParseReportMarkerFrontmatter_QuotesAndComments(t *testing.T) {
	body := "# generated by agent\npath: \"/tmp/q.md\"\ntitle: 'Quoted Title'"
	info, ok := parseReportMarkerFrontmatter(body)
	if !ok {
		t.Fatal("expected ok=true")
	}
	if info.Path != "/tmp/q.md" {
		t.Errorf("path = %q, want /tmp/q.md (quotes should be stripped)", info.Path)
	}
	if info.Title != "Quoted Title" {
		t.Errorf("title = %q, want Quoted Title", info.Title)
	}
}

// TestStripReportMarkerFences: persisted agent prose and rendered chat
// bubbles must not show the raw fence — it's a signal, not display
// content. The stripper must remove the fence and its body cleanly,
// leaving surrounding prose intact.
func TestStripReportMarkerFences(t *testing.T) {
	in := "Here is your analysis.\n\n```astonish-report\npath: /tmp/r.md\ntitle: T\n```\n\nLet me know if you want changes."
	out := stripReportMarkerFences(in)
	if contains(out, "astonish-report") || contains(out, "/tmp/r.md") {
		t.Errorf("fence not stripped: %q", out)
	}
	if !contains(out, "Here is your analysis.") {
		t.Errorf("leading prose lost: %q", out)
	}
	if !contains(out, "Let me know if you want changes.") {
		t.Errorf("trailing prose lost: %q", out)
	}
}

// TestStripReportMarkerFences_Multiple: the agent may emit multiple
// reports in a single turn. Every fence must be stripped, not just the
// first.
func TestStripReportMarkerFences_Multiple(t *testing.T) {
	in := "```astonish-report\npath: /tmp/a.md\n```\n\nAnd:\n\n```astonish-report\npath: /tmp/b.md\n```"
	out := stripReportMarkerFences(in)
	if contains(out, "astonish-report") || contains(out, "/tmp/a.md") || contains(out, "/tmp/b.md") {
		t.Errorf("not all fences stripped: %q", out)
	}
}

// TestDetectAndEmitReportMarkers_HappyPath: end-to-end pipeline through
// the runner. Given a turn with a write_file artifact event AND a
// matching ```astonish-report fence in the agent text, the runner must
// emit exactly one report_marker event with path+title.
func TestDetectAndEmitReportMarkers_HappyPath(t *testing.T) {
	runner := newChatRunner("test-rm-happy", studioChatUserID, true)
	ch := runner.Subscribe("test")
	defer runner.Unsubscribe("test")

	// Same-turn artifact event — required for the path-match gate.
	runner.emitEvent("artifact", map[string]any{
		"path":     "/tmp/report.md",
		"toolName": "write_file",
	})
	// Drain the artifact event so the test channel doesn't fill up; we
	// only care about the report_marker event below.
	<-ch

	// Agent prose containing the fence.
	runner.emitEvent("text", map[string]any{
		"text": "Done.\n\n```astonish-report\npath: /tmp/report.md\ntitle: My Report\n```\n",
	})
	<-ch // drain text event

	// Trigger the post-processor with a nil session service so persistence
	// is a no-op (persistReportMarker guards against nil) but the emit
	// path runs in full.
	runner.detectAndEmitReportMarkers(nil)

	select {
	case ev := <-ch:
		if ev.Type != "report_marker" {
			t.Fatalf("expected report_marker event, got %q", ev.Type)
		}
		if got := ev.Data["path"]; got != "/tmp/report.md" {
			t.Errorf("path = %v, want /tmp/report.md", got)
		}
		if got := ev.Data["title"]; got != "My Report" {
			t.Errorf("title = %v, want My Report", got)
		}
	case <-time.After(time.Second):
		t.Fatal("timed out waiting for report_marker event")
	}
}

// TestDetectAndEmitReportMarkers_PathMismatch: a fence whose path does
// NOT correspond to any same-turn artifact must be silently dropped.
// This is the safety property that prevents an LLM hallucinating a path
// from fabricating a fake report card.
func TestDetectAndEmitReportMarkers_PathMismatch(t *testing.T) {
	runner := newChatRunner("test-rm-mismatch", studioChatUserID, true)
	ch := runner.Subscribe("test")
	defer runner.Unsubscribe("test")

	runner.emitEvent("artifact", map[string]any{
		"path":     "/tmp/actual.md",
		"toolName": "write_file",
	})
	<-ch
	runner.emitEvent("text", map[string]any{
		"text": "```astonish-report\npath: /tmp/different.md\n```",
	})
	<-ch

	runner.detectAndEmitReportMarkers(nil)

	select {
	case ev := <-ch:
		t.Fatalf("expected NO report_marker event for mismatched path; got %q (%v)", ev.Type, ev.Data)
	case <-time.After(100 * time.Millisecond):
		// expected: no event
	}
}

// TestDetectAndEmitReportMarkers_Dedup: if the agent re-emits the same
// path across multiple fences in one turn (a known LLM tic), only one
// report_marker event must be sent. Prevents duplicate UI updates.
func TestDetectAndEmitReportMarkers_Dedup(t *testing.T) {
	runner := newChatRunner("test-rm-dedup", studioChatUserID, true)
	ch := runner.Subscribe("test")
	defer runner.Unsubscribe("test")

	runner.emitEvent("artifact", map[string]any{
		"path":     "/tmp/dup.md",
		"toolName": "write_file",
	})
	<-ch
	runner.emitEvent("text", map[string]any{
		"text": "```astonish-report\npath: /tmp/dup.md\ntitle: First\n```\n\n```astonish-report\npath: /tmp/dup.md\ntitle: Second\n```",
	})
	<-ch

	runner.detectAndEmitReportMarkers(nil)

	count := 0
	for {
		select {
		case ev := <-ch:
			if ev.Type == "report_marker" {
				count++
			}
		case <-time.After(100 * time.Millisecond):
			if count != 1 {
				t.Fatalf("expected exactly 1 report_marker event after dedup, got %d", count)
			}
			return
		}
	}
}

// TestJoinReportMarkers: the projection step that runs at session-detail
// load time. Given a slice of reconstructed artifacts and a markers map,
// only artifacts whose path is keyed in the map must be flagged
// IsReport=true with the matching title. All others must be untouched.
func TestCollectArtifactsKeepsLatestMutationForPath(t *testing.T) {
	events := testEvents{
		artifactToolCallEvent("inv-1", "call-1", "write_file", map[string]any{"file_path": "/tmp/report.md", "content": "2025"}),
		toolResponseEvent("inv-1", "call-1", "write_file", map[string]any{"path": "/tmp/report.md"}),
		artifactToolCallEvent("inv-2", "call-2", "edit_file", map[string]any{"path": "/tmp/report.md", "old_string": "2025", "new_string": "2026"}),
		toolResponseEvent("inv-2", "call-2", "edit_file", map[string]any{"path": "/tmp/report.md"}),
	}

	artifacts := collectArtifacts(events)
	if len(artifacts) != 1 {
		t.Fatalf("len(artifacts) = %d, want 1: %+v", len(artifacts), artifacts)
	}
	if artifacts[0].ToolName != "edit_file" {
		t.Fatalf("ToolName = %q, want edit_file", artifacts[0].ToolName)
	}
}

func TestReadArtifactContentFromEventsAppliesEditFileMutations(t *testing.T) {
	events := testEvents{
		artifactToolCallEvent("inv-1", "call-1", "write_file", map[string]any{"file_path": "/tmp/report.md", "content": "# Report\n\nYear: 2025\nStatus: draft\n"}),
		artifactToolCallEvent("inv-2", "call-2", "edit_file", map[string]any{"path": "/tmp/report.md", "old_string": "2025", "new_string": "2026"}),
		artifactToolCallEvent("inv-3", "call-3", "edit_file", map[string]any{"path": "/tmp/report.md", "old_string": "draft", "new_string": "final"}),
	}

	content, ok := readArtifactContentFromEvents(events, "/tmp/report.md")
	if !ok {
		t.Fatal("expected fallback content")
	}
	want := "# Report\n\nYear: 2026\nStatus: final\n"
	if content != want {
		t.Fatalf("content = %q, want %q", content, want)
	}
}

func TestReadArtifactContentFromEventsAppliesReplaceAllEdit(t *testing.T) {
	events := testEvents{
		artifactToolCallEvent("inv-1", "call-1", "write_file", map[string]any{"file_path": "/tmp/report.md", "content": "2025 and 2025"}),
		artifactToolCallEvent("inv-2", "call-2", "edit_file", map[string]any{"path": "/tmp/report.md", "old_string": "2025", "new_string": "2026", "replace_all": true}),
	}

	content, ok := readArtifactContentFromEvents(events, "/tmp/report.md")
	if !ok {
		t.Fatal("expected fallback content")
	}
	if content != "2026 and 2026" {
		t.Fatalf("content = %q, want %q", content, "2026 and 2026")
	}
}

func TestReadArtifactContentFromEventsIgnoresFailedEdit(t *testing.T) {
	events := testEvents{
		artifactToolCallEvent("inv-1", "call-1", "write_file", map[string]any{"file_path": "/tmp/report.md", "content": "Year: 2025"}),
		artifactToolCallEvent("inv-2", "call-2", "edit_file", map[string]any{"path": "/tmp/report.md", "old_string": "2025", "new_string": "2026"}),
		toolResponseEvent("inv-2", "call-2", "edit_file", map[string]any{"error": "old_string not found"}),
	}

	content, ok := readArtifactContentFromEvents(events, "/tmp/report.md")
	if !ok {
		t.Fatal("expected fallback content")
	}
	if content != "Year: 2025" {
		t.Fatalf("content = %q, want original content after failed edit", content)
	}
}

func artifactToolCallEvent(invocationID, callID, name string, args map[string]any) *session.Event {
	return &session.Event{
		InvocationID: invocationID,
		LLMResponse: model.LLMResponse{
			Content: &genai.Content{
				Role: "model",
				Parts: []*genai.Part{{FunctionCall: &genai.FunctionCall{
					ID:   callID,
					Name: name,
					Args: args,
				}}},
			},
		},
	}
}

func toolResponseEvent(invocationID, callID, name string, response map[string]any) *session.Event {
	return &session.Event{
		InvocationID: invocationID,
		LLMResponse: model.LLMResponse{
			Content: &genai.Content{
				Role: "model",
				Parts: []*genai.Part{{FunctionResponse: &genai.FunctionResponse{
					ID:       callID,
					Name:     name,
					Response: response,
				}}},
			},
		},
	}
}

func TestJoinReportMarkers(t *testing.T) {
	artifacts := []ArtifactInfo{
		{Path: "/tmp/a.md", FileName: "a.md", FileType: "Markdown", ToolName: "write_file"},
		{Path: "/tmp/b.py", FileName: "b.py", FileType: "Python", ToolName: "write_file"},
		{Path: "/tmp/c.md", FileName: "c.md", FileType: "Markdown", ToolName: "edit_file"},
	}
	markers := map[string]string{
		"/tmp/a.md": "A Title",
		"/tmp/c.md": "", // marker without title — IsReport must still flip
	}
	out := joinReportMarkers(artifacts, markers)

	if !out[0].IsReport || out[0].ReportTitle != "A Title" {
		t.Errorf("a.md = %+v, want IsReport=true ReportTitle=A Title", out[0])
	}
	if out[1].IsReport {
		t.Errorf("b.py = %+v, want IsReport=false (no marker)", out[1])
	}
	if !out[2].IsReport || out[2].ReportTitle != "" {
		t.Errorf("c.md = %+v, want IsReport=true ReportTitle empty", out[2])
	}

	// Original slice must NOT be mutated — joinReportMarkers must return
	// a defensive copy so caller-held references don't observe changes.
	if artifacts[0].IsReport {
		t.Error("input slice was mutated; joinReportMarkers must return a fresh copy")
	}
}

// TestCollectReportMarkers_RoundTrip: persist → reconstruct round-trip.
// Given a session whose event log contains persisted report-marker text
// events (the format produced by persistReportMarker), the collector
// must rebuild the path -> title map exactly.
func TestCollectReportMarkers_RoundTrip(t *testing.T) {
	events := testEvents{
		textEvent("inv-1", "model", reportMarkerPrefix+`{"path":"/tmp/r1.md","title":"Report One"}`),
		textEvent("inv-2", "model", reportMarkerPrefix+`{"path":"/tmp/r2.md"}`),
		// Last-write-wins for repeated path: the second title for r1 must overwrite the first.
		textEvent("inv-3", "model", reportMarkerPrefix+`{"path":"/tmp/r1.md","title":"Updated Title"}`),
		// Non-marker text must be ignored entirely.
		textEvent("inv-4", "model", "regular agent prose, not a marker"),
	}
	got := collectReportMarkers(events)

	if got["/tmp/r1.md"] != "Updated Title" {
		t.Errorf("r1 title = %q, want Updated Title (last-write-wins)", got["/tmp/r1.md"])
	}
	if title, ok := got["/tmp/r2.md"]; !ok || title != "" {
		t.Errorf("r2 = (%q, %v), want present with empty title", title, ok)
	}
	if len(got) != 2 {
		t.Errorf("len(markers) = %d, want 2", len(got))
	}
}

// TestTryParseReportMarkerMessage: the playback-loop hook that suppresses
// persisted markers from the rendered chat transcript. Only texts with
// the marker prefix should be reported as consumed; everything else
// must pass through to normal coalescing.
func TestTryParseReportMarkerMessage(t *testing.T) {
	if !tryParseReportMarkerMessage(reportMarkerPrefix + `{"path":"/x"}`) {
		t.Error("marker text not recognized")
	}
	if tryParseReportMarkerMessage("[app_preview]{}") {
		t.Error("app_preview text falsely recognized as report marker")
	}
	if tryParseReportMarkerMessage("plain prose") {
		t.Error("plain text falsely recognized as report marker")
	}
}

// contains is a small helper to avoid pulling in strings just for the
// test file's substring assertions.
func contains(haystack, needle string) bool {
	for i := 0; i+len(needle) <= len(haystack); i++ {
		if haystack[i:i+len(needle)] == needle {
			return true
		}
	}
	return false
}
