package docker

// In-container paths and env names. These MUST match the sandbox-base
// entrypoint generated by pkg/sandbox/k8s/overlay_entrypoint.go. Docker
// duplicates the constants instead of importing k8s (import cycle).
const (
	mountLayers  = "/mnt/astonish-layers"
	mountUppers  = "/mnt/astonish-uppers"
	mountOverlay = "/var/astonish/overlay"
	mountUpper   = mountOverlay + "/upper"
	mountWork    = mountOverlay + "/work"
	mountRootfs  = "/sandbox/rootfs"

	astonishShell = "/usr/local/bin/astonish-shell"

	envSessionID  = "ASTONISH_SESSION_ID"
	envLayerChain = "ASTONISH_LAYER_CHAIN"
	envUpperDir   = "ASTONISH_UPPER_DIR"
	envWorkDir    = "ASTONISH_WORK_DIR"
	envLayersDir  = "ASTONISH_LAYERS_DIR"
	envUppersDir  = "ASTONISH_UPPERS_DIR"
	envHandoff    = "ASTONISH_HANDOFF"
	envHandoffArg = "ASTONISH_HANDOFF_ARGS"

	layerChainFile = "layer-chain.txt"
)
