// Code generated by ent, DO NOT EDIT.

package platformslidetemplate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the platformslidetemplate type in the database.
	Label = "platform_slide_template"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSchemaVersion holds the string denoting the schema_version field in the database.
	FieldSchemaVersion = "schema_version"
	// FieldSkin holds the string denoting the skin field in the database.
	FieldSkin = "skin"
	// FieldTokens holds the string denoting the tokens field in the database.
	FieldTokens = "tokens"
	// FieldAssets holds the string denoting the assets field in the database.
	FieldAssets = "assets"
	// FieldPalettes holds the string denoting the palettes field in the database.
	FieldPalettes = "palettes"
	// FieldArchetypes holds the string denoting the archetypes field in the database.
	FieldArchetypes = "archetypes"
	// FieldTemplateModel holds the string denoting the template_model field in the database.
	FieldTemplateModel = "template_model"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the platformslidetemplate in the database.
	Table = "platform_slide_templates"
)

// Columns holds all SQL columns for platformslidetemplate fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldLabel,
	FieldDescription,
	FieldSchemaVersion,
	FieldSkin,
	FieldTokens,
	FieldAssets,
	FieldPalettes,
	FieldArchetypes,
	FieldTemplateModel,
	FieldCreatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultLabel holds the default value on creation for the "label" field.
	DefaultLabel string
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultSchemaVersion holds the default value on creation for the "schema_version" field.
	DefaultSchemaVersion int
	// DefaultSkin holds the default value on creation for the "skin" field.
	DefaultSkin string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the PlatformSlideTemplate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// BySchemaVersion orders the results by the schema_version field.
func BySchemaVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSchemaVersion, opts...).ToFunc()
}

// BySkin orders the results by the skin field.
func BySkin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkin, opts...).ToFunc()
}

// ByTemplateModel orders the results by the template_model field.
func ByTemplateModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTemplateModel, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
