// Code generated by ent, DO NOT EDIT.

package oauthsigningkey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/SAP/astonish/ent/platform/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLTE(FieldID, id))
}

// KeyID applies equality check predicate on the "key_id" field. It's identical to KeyIDEQ.
func KeyID(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldKeyID, v))
}

// Algorithm applies equality check predicate on the "algorithm" field. It's identical to AlgorithmEQ.
func Algorithm(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldAlgorithm, v))
}

// EncryptedPrivateKey applies equality check predicate on the "encrypted_private_key" field. It's identical to EncryptedPrivateKeyEQ.
func EncryptedPrivateKey(v []byte) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldEncryptedPrivateKey, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldCreatedAt, v))
}

// NotAfter applies equality check predicate on the "not_after" field. It's identical to NotAfterEQ.
func NotAfter(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldNotAfter, v))
}

// KeyIDEQ applies the EQ predicate on the "key_id" field.
func KeyIDEQ(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldKeyID, v))
}

// KeyIDNEQ applies the NEQ predicate on the "key_id" field.
func KeyIDNEQ(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNEQ(FieldKeyID, v))
}

// KeyIDIn applies the In predicate on the "key_id" field.
func KeyIDIn(vs ...string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIn(FieldKeyID, vs...))
}

// KeyIDNotIn applies the NotIn predicate on the "key_id" field.
func KeyIDNotIn(vs ...string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotIn(FieldKeyID, vs...))
}

// KeyIDGT applies the GT predicate on the "key_id" field.
func KeyIDGT(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGT(FieldKeyID, v))
}

// KeyIDGTE applies the GTE predicate on the "key_id" field.
func KeyIDGTE(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGTE(FieldKeyID, v))
}

// KeyIDLT applies the LT predicate on the "key_id" field.
func KeyIDLT(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLT(FieldKeyID, v))
}

// KeyIDLTE applies the LTE predicate on the "key_id" field.
func KeyIDLTE(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLTE(FieldKeyID, v))
}

// KeyIDContains applies the Contains predicate on the "key_id" field.
func KeyIDContains(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldContains(FieldKeyID, v))
}

// KeyIDHasPrefix applies the HasPrefix predicate on the "key_id" field.
func KeyIDHasPrefix(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldHasPrefix(FieldKeyID, v))
}

// KeyIDHasSuffix applies the HasSuffix predicate on the "key_id" field.
func KeyIDHasSuffix(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldHasSuffix(FieldKeyID, v))
}

// KeyIDEqualFold applies the EqualFold predicate on the "key_id" field.
func KeyIDEqualFold(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEqualFold(FieldKeyID, v))
}

// KeyIDContainsFold applies the ContainsFold predicate on the "key_id" field.
func KeyIDContainsFold(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldContainsFold(FieldKeyID, v))
}

// AlgorithmEQ applies the EQ predicate on the "algorithm" field.
func AlgorithmEQ(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldAlgorithm, v))
}

// AlgorithmNEQ applies the NEQ predicate on the "algorithm" field.
func AlgorithmNEQ(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNEQ(FieldAlgorithm, v))
}

// AlgorithmIn applies the In predicate on the "algorithm" field.
func AlgorithmIn(vs ...string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIn(FieldAlgorithm, vs...))
}

// AlgorithmNotIn applies the NotIn predicate on the "algorithm" field.
func AlgorithmNotIn(vs ...string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotIn(FieldAlgorithm, vs...))
}

// AlgorithmGT applies the GT predicate on the "algorithm" field.
func AlgorithmGT(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGT(FieldAlgorithm, v))
}

// AlgorithmGTE applies the GTE predicate on the "algorithm" field.
func AlgorithmGTE(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGTE(FieldAlgorithm, v))
}

// AlgorithmLT applies the LT predicate on the "algorithm" field.
func AlgorithmLT(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLT(FieldAlgorithm, v))
}

// AlgorithmLTE applies the LTE predicate on the "algorithm" field.
func AlgorithmLTE(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLTE(FieldAlgorithm, v))
}

// AlgorithmContains applies the Contains predicate on the "algorithm" field.
func AlgorithmContains(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldContains(FieldAlgorithm, v))
}

// AlgorithmHasPrefix applies the HasPrefix predicate on the "algorithm" field.
func AlgorithmHasPrefix(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldHasPrefix(FieldAlgorithm, v))
}

// AlgorithmHasSuffix applies the HasSuffix predicate on the "algorithm" field.
func AlgorithmHasSuffix(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldHasSuffix(FieldAlgorithm, v))
}

// AlgorithmEqualFold applies the EqualFold predicate on the "algorithm" field.
func AlgorithmEqualFold(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEqualFold(FieldAlgorithm, v))
}

// AlgorithmContainsFold applies the ContainsFold predicate on the "algorithm" field.
func AlgorithmContainsFold(v string) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldContainsFold(FieldAlgorithm, v))
}

// EncryptedPrivateKeyEQ applies the EQ predicate on the "encrypted_private_key" field.
func EncryptedPrivateKeyEQ(v []byte) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldEncryptedPrivateKey, v))
}

// EncryptedPrivateKeyNEQ applies the NEQ predicate on the "encrypted_private_key" field.
func EncryptedPrivateKeyNEQ(v []byte) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNEQ(FieldEncryptedPrivateKey, v))
}

// EncryptedPrivateKeyIn applies the In predicate on the "encrypted_private_key" field.
func EncryptedPrivateKeyIn(vs ...[]byte) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIn(FieldEncryptedPrivateKey, vs...))
}

// EncryptedPrivateKeyNotIn applies the NotIn predicate on the "encrypted_private_key" field.
func EncryptedPrivateKeyNotIn(vs ...[]byte) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotIn(FieldEncryptedPrivateKey, vs...))
}

// EncryptedPrivateKeyGT applies the GT predicate on the "encrypted_private_key" field.
func EncryptedPrivateKeyGT(v []byte) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGT(FieldEncryptedPrivateKey, v))
}

// EncryptedPrivateKeyGTE applies the GTE predicate on the "encrypted_private_key" field.
func EncryptedPrivateKeyGTE(v []byte) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGTE(FieldEncryptedPrivateKey, v))
}

// EncryptedPrivateKeyLT applies the LT predicate on the "encrypted_private_key" field.
func EncryptedPrivateKeyLT(v []byte) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLT(FieldEncryptedPrivateKey, v))
}

// EncryptedPrivateKeyLTE applies the LTE predicate on the "encrypted_private_key" field.
func EncryptedPrivateKeyLTE(v []byte) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLTE(FieldEncryptedPrivateKey, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLTE(FieldCreatedAt, v))
}

// NotAfterEQ applies the EQ predicate on the "not_after" field.
func NotAfterEQ(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldEQ(FieldNotAfter, v))
}

// NotAfterNEQ applies the NEQ predicate on the "not_after" field.
func NotAfterNEQ(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNEQ(FieldNotAfter, v))
}

// NotAfterIn applies the In predicate on the "not_after" field.
func NotAfterIn(vs ...time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIn(FieldNotAfter, vs...))
}

// NotAfterNotIn applies the NotIn predicate on the "not_after" field.
func NotAfterNotIn(vs ...time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotIn(FieldNotAfter, vs...))
}

// NotAfterGT applies the GT predicate on the "not_after" field.
func NotAfterGT(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGT(FieldNotAfter, v))
}

// NotAfterGTE applies the GTE predicate on the "not_after" field.
func NotAfterGTE(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldGTE(FieldNotAfter, v))
}

// NotAfterLT applies the LT predicate on the "not_after" field.
func NotAfterLT(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLT(FieldNotAfter, v))
}

// NotAfterLTE applies the LTE predicate on the "not_after" field.
func NotAfterLTE(v time.Time) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldLTE(FieldNotAfter, v))
}

// NotAfterIsNil applies the IsNil predicate on the "not_after" field.
func NotAfterIsNil() predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldIsNull(FieldNotAfter))
}

// NotAfterNotNil applies the NotNil predicate on the "not_after" field.
func NotAfterNotNil() predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.FieldNotNull(FieldNotAfter))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthSigningKey) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthSigningKey) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthSigningKey) predicate.OAuthSigningKey {
	return predicate.OAuthSigningKey(sql.NotPredicates(p))
}
