// Package events defines the mode-agnostic chat event model shared by the
// local (ADK) and remote (SSE) TUI backends. The bubbletea app reduces these
// events into transcript state; it never talks to ADK or HTTP directly.
package events

// Kind identifies a chat event. Values mirror Studio SSE types where possible
// so the remote backend can map 1:1 and soft-degrade unknown kinds.
type Kind string

const (
	KindSession       Kind = "session"
	KindText          Kind = "text"
	KindThinking      Kind = "thinking"
	KindToolCall      Kind = "tool_call"
	KindToolResult    Kind = "tool_result"
	KindApproval      Kind = "approval"
	KindNetworkDenial Kind = "network_denial"
	KindAutoApproved  Kind = "auto_approved"
	KindArtifact      Kind = "artifact"
	KindReportMarker  Kind = "report_marker"
	KindUsage         Kind = "usage"
	KindError         Kind = "error"
	KindErrorInfo     Kind = "error_info"
	KindDone          Kind = "done"
	KindSystem        Kind = "system"
	KindSubagent      Kind = "subagent"
	KindSessionTitle  Kind = "session_title"
	KindModelChanged  Kind = "model_changed"
	KindStatus        Kind = "status"     // spinner / live status text
	KindUser          Kind = "user"       // local echo of user message
	KindDelegation    Kind = "delegation" // sub-agent delegation lifecycle
	KindPlan          Kind = "plan"       // plan document plus its approval lifecycle
)

// PlanStatus is the approval lifecycle owned by a plan transcript item.
type PlanStatus string

const (
	PlanPending          PlanStatus = "pending"
	PlanApproved         PlanStatus = "approved"
	PlanChangesRequested PlanStatus = "changes_requested"
	PlanDeclined         PlanStatus = "declined"
)

// Usage holds token accounting for a turn.
type Usage struct {
	Input  int64
	Output int64
	Total  int64
	// Estimated marks a usage reading derived locally (e.g. from context size)
	// rather than reported by the provider. Estimated readings update the
	// context-occupancy figure but are NOT accumulated into cumulative session
	// usage, since each one represents the full current context, not a delta.
	Estimated bool
}

// NetworkDenial describes one outbound connection blocked by the sandbox proxy.
type NetworkDenial struct {
	ChunkID        string
	Host           string
	Port           uint32
	Binary         string
	Rationale      string
	SecurityNotes  string
	BroaderPattern string
}

// Artifact describes a file generated by an agent turn.
type Artifact struct {
	Path        string
	FileName    string
	FileType    string
	ToolName    string
	IsReport    bool
	ReportTitle string
}

// DelegationTask describes one sub-task in a delegation event.
type DelegationTask struct {
	Name        string
	Description string
	PlanStep    string
}

// Event is one unit of chat progress. Fields are optional by Kind.
type Event struct {
	Kind Kind

	// Text is used by KindText, KindThinking, KindSystem, KindError, KindStatus.
	Text string

	// Tool fields for KindToolCall / KindToolResult / KindApproval / KindAutoApproved.
	ToolName string
	ToolID   string
	Args     map[string]any
	Result   any
	Options  []string // approval options

	// ApprovalKind distinguishes code-mode authorization prompts:
	// "" (generic tool approval), "tool" (not-whitelisted tool execution),
	// "folder" (out-of-project filesystem access), or "plan" (announce_plan
	// approval). Paths holds the requested out-of-project paths for a "folder"
	// prompt. PlanContext/PlanWhatNotToDo/PlanVerification carry the optional
	// narrative sections from the plan document for "plan" approvals.
	ApprovalKind     string
	Paths            []string
	PlanContext      string
	PlanWhatNotToDo  string
	PlanVerification string
	// PlanStatus makes the document and its approval lifecycle one atomic event.
	PlanStatus PlanStatus

	// SessionID for KindSession / KindSessionTitle.
	SessionID string
	Title     string

	// Usage for KindUsage.
	Usage *Usage

	// Network denial fields for KindNetworkDenial.
	NetworkDenials []NetworkDenial
	SandboxName    string

	// Structured error (KindErrorInfo).
	ErrorTitle      string
	ErrorReason     string
	ErrorSuggestion string

	// Provider/model for KindModelChanged.
	Provider string
	Model    string

	// Artifact for KindArtifact.
	Artifact *Artifact

	// Meta holds optional backend-specific keys without expanding the struct.
	Meta map[string]any

	// Delegation fields for KindDelegation.
	DelegationType     string           // "start", "task_start", "task_complete", "task_failed", "done"
	DelegationTasks    []DelegationTask // all tasks (only for "start")
	DelegationTaskName string           // task name (for task_start/task_complete/task_failed)
	DelegationDuration string           // human-readable duration (for task_complete/task_failed)
	DelegationError    string           // error message (for task_failed)

	// Delegation activity fields (for task_tool_call/task_tool_result/task_text).
	DelegationToolName   string
	DelegationToolArgs   map[string]any
	DelegationToolResult any
	DelegationText       string
}

// NewText returns a streaming agent text event.
func NewText(s string) Event {
	return Event{Kind: KindText, Text: s}
}

// NewSystem returns a system notice event.
func NewSystem(s string) Event {
	return Event{Kind: KindSystem, Text: s}
}

// NewError returns a simple error event.
func NewError(s string) Event {
	return Event{Kind: KindError, Text: s}
}

// NewStatus returns a live status / spinner text event.
func NewStatus(s string) Event {
	return Event{Kind: KindStatus, Text: s}
}

// NewUser returns a user message echo event.
func NewUser(s string) Event {
	return Event{Kind: KindUser, Text: s}
}

// NewDone marks the end of a turn stream.
func NewDone() Event {
	return Event{Kind: KindDone}
}

// NewToolCall returns a tool invocation event.
func NewToolCall(name, id string, args map[string]any) Event {
	return Event{Kind: KindToolCall, ToolName: name, ToolID: id, Args: args}
}

// NewToolResult returns a tool result event.
func NewToolResult(name, id string, result any) Event {
	return Event{Kind: KindToolResult, ToolName: name, ToolID: id, Result: result}
}

// NewApproval returns a tool approval request.
func NewApproval(name string, args map[string]any, options []string) Event {
	return Event{Kind: KindApproval, ToolName: name, Args: args, Options: options}
}

// NewAuthorizationApproval returns a code-mode authorization request carrying
// the approval kind ("tool" or "folder") and, for folder requests, the
// out-of-project paths being requested.
func NewAuthorizationApproval(name string, args map[string]any, options []string, kind string, paths []string) Event {
	return Event{
		Kind:         KindApproval,
		ToolName:     name,
		Args:         args,
		Options:      options,
		ApprovalKind: kind,
		Paths:        paths,
	}
}

// NewPlan returns one atomic plan document and approval-lifecycle event.
func NewPlan(content string, status PlanStatus) Event {
	if status == "" {
		status = PlanPending
	}
	return Event{
		Kind:         KindPlan,
		Text:         content,
		ToolName:     "announce_plan",
		Options:      []string{"Approve & implement", "Request changes", "Decline"},
		ApprovalKind: "plan",
		PlanStatus:   status,
	}
}

// NewNetworkDenial returns a network authorization request.
func NewNetworkDenial(sessionID, sandboxName string, denials []NetworkDenial) Event {
	return Event{Kind: KindNetworkDenial, SessionID: sessionID, SandboxName: sandboxName, NetworkDenials: denials}
}

// NewDelegation returns a delegation lifecycle event.
func NewDelegation(dtype string) Event {
	return Event{Kind: KindDelegation, DelegationType: dtype}
}

// NewDelegationStart returns a delegation start event with the full task list.
func NewDelegationStart(tasks []DelegationTask) Event {
	return Event{Kind: KindDelegation, DelegationType: "start", DelegationTasks: tasks}
}

// NewDelegationTaskUpdate returns a per-task lifecycle event (task_start, task_complete, task_failed).
func NewDelegationTaskUpdate(dtype, taskName, duration, errMsg string) Event {
	return Event{
		Kind:               KindDelegation,
		DelegationType:     dtype,
		DelegationTaskName: taskName,
		DelegationDuration: duration,
		DelegationError:    errMsg,
	}
}

// NewDelegationTaskActivity returns a per-task activity event (tool_call, tool_result, text).
func NewDelegationTaskActivity(dtype, taskName, toolName string, args map[string]any, result any, text string) Event {
	return Event{
		Kind:                 KindDelegation,
		DelegationType:       dtype,
		DelegationTaskName:   taskName,
		DelegationToolName:   toolName,
		DelegationToolArgs:   args,
		DelegationToolResult: result,
		DelegationText:       text,
	}
}
