// Code generated by ent, DO NOT EDIT.

package org

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SAP/astonish/ent/org/orga2aagent"
	"github.com/google/uuid"
)

// OrgA2AAgent is the model entity for the OrgA2AAgent schema.
type OrgA2AAgent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// CredentialName holds the value of the "credential_name" field.
	CredentialName *string `json:"credential_name,omitempty"`
	// AuthType holds the value of the "auth_type" field.
	AuthType string `json:"auth_type,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Headers holds the value of the "headers" field.
	Headers map[string]string `json:"headers,omitempty"`
	// Timeout holds the value of the "timeout" field.
	Timeout *string `json:"timeout,omitempty"`
	// CachedCard holds the value of the "cached_card" field.
	CachedCard []uint8 `json:"cached_card,omitempty"`
	// CachedSkills holds the value of the "cached_skills" field.
	CachedSkills []interface{} `json:"cached_skills,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy uuid.UUID `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrgA2AAgent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case orga2aagent.FieldHeaders, orga2aagent.FieldCachedCard, orga2aagent.FieldCachedSkills:
			values[i] = new([]byte)
		case orga2aagent.FieldEnabled:
			values[i] = new(sql.NullBool)
		case orga2aagent.FieldName, orga2aagent.FieldURL, orga2aagent.FieldCredentialName, orga2aagent.FieldAuthType, orga2aagent.FieldTimeout:
			values[i] = new(sql.NullString)
		case orga2aagent.FieldCreatedAt, orga2aagent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case orga2aagent.FieldID, orga2aagent.FieldCreatedBy:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrgA2AAgent fields.
func (_m *OrgA2AAgent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case orga2aagent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case orga2aagent.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case orga2aagent.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case orga2aagent.FieldCredentialName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credential_name", values[i])
			} else if value.Valid {
				_m.CredentialName = new(string)
				*_m.CredentialName = value.String
			}
		case orga2aagent.FieldAuthType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_type", values[i])
			} else if value.Valid {
				_m.AuthType = value.String
			}
		case orga2aagent.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case orga2aagent.FieldHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Headers); err != nil {
					return fmt.Errorf("unmarshal field headers: %w", err)
				}
			}
		case orga2aagent.FieldTimeout:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field timeout", values[i])
			} else if value.Valid {
				_m.Timeout = new(string)
				*_m.Timeout = value.String
			}
		case orga2aagent.FieldCachedCard:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field cached_card", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CachedCard); err != nil {
					return fmt.Errorf("unmarshal field cached_card: %w", err)
				}
			}
		case orga2aagent.FieldCachedSkills:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field cached_skills", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CachedSkills); err != nil {
					return fmt.Errorf("unmarshal field cached_skills: %w", err)
				}
			}
		case orga2aagent.FieldCreatedBy:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value != nil {
				_m.CreatedBy = *value
			}
		case orga2aagent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case orga2aagent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrgA2AAgent.
// This includes values selected through modifiers, order, etc.
func (_m *OrgA2AAgent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OrgA2AAgent.
// Note that you need to call OrgA2AAgent.Unwrap() before calling this method if this OrgA2AAgent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OrgA2AAgent) Update() *OrgA2AAgentUpdateOne {
	return NewOrgA2AAgentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OrgA2AAgent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OrgA2AAgent) Unwrap() *OrgA2AAgent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("org: OrgA2AAgent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OrgA2AAgent) String() string {
	var builder strings.Builder
	builder.WriteString("OrgA2AAgent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	if v := _m.CredentialName; v != nil {
		builder.WriteString("credential_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("auth_type=")
	builder.WriteString(_m.AuthType)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.Headers))
	builder.WriteString(", ")
	if v := _m.Timeout; v != nil {
		builder.WriteString("timeout=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("cached_card=")
	builder.WriteString(fmt.Sprintf("%v", _m.CachedCard))
	builder.WriteString(", ")
	builder.WriteString("cached_skills=")
	builder.WriteString(fmt.Sprintf("%v", _m.CachedSkills))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OrgA2AAgents is a parsable slice of OrgA2AAgent.
type OrgA2AAgents []*OrgA2AAgent
