// Code generated by ent, DO NOT EDIT.

package org

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/org/orgslidetemplate"
	"github.com/SAP/astonish/ent/org/predicate"
)

// OrgSlideTemplateDelete is the builder for deleting a OrgSlideTemplate entity.
type OrgSlideTemplateDelete struct {
	config
	hooks    []Hook
	mutation *OrgSlideTemplateMutation
}

// Where appends a list predicates to the OrgSlideTemplateDelete builder.
func (_d *OrgSlideTemplateDelete) Where(ps ...predicate.OrgSlideTemplate) *OrgSlideTemplateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OrgSlideTemplateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrgSlideTemplateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OrgSlideTemplateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(orgslidetemplate.Table, sqlgraph.NewFieldSpec(orgslidetemplate.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OrgSlideTemplateDeleteOne is the builder for deleting a single OrgSlideTemplate entity.
type OrgSlideTemplateDeleteOne struct {
	_d *OrgSlideTemplateDelete
}

// Where appends a list predicates to the OrgSlideTemplateDelete builder.
func (_d *OrgSlideTemplateDeleteOne) Where(ps ...predicate.OrgSlideTemplate) *OrgSlideTemplateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OrgSlideTemplateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{orgslidetemplate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrgSlideTemplateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
