// Code generated by ent, DO NOT EDIT.

package personal

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SAP/astonish/ent/personal/deck"
	"github.com/google/uuid"
)

// Deck is the model entity for the Deck schema.
type Deck struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// SchemaVersion holds the value of the "schema_version" field.
	SchemaVersion int `json:"schema_version,omitempty"`
	// Theme holds the value of the "theme" field.
	Theme map[string]string `json:"theme,omitempty"`
	// Assets holds the value of the "assets" field.
	Assets map[string]string `json:"assets,omitempty"`
	// TemplateModel holds the value of the "template_model" field.
	TemplateModel string `json:"template_model,omitempty"`
	// ThumbnailReady holds the value of the "thumbnail_ready" field.
	ThumbnailReady bool `json:"thumbnail_ready,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// SourceSlug holds the value of the "source_slug" field.
	SourceSlug string `json:"source_slug,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DeckQuery when eager-loading is set.
	Edges        DeckEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DeckEdges holds the relations/edges for other nodes in the graph.
type DeckEdges struct {
	// Slides holds the value of the slides edge.
	Slides []*Slide `json:"slides,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SlidesOrErr returns the Slides value or an error if the edge
// was not loaded in eager-loading.
func (e DeckEdges) SlidesOrErr() ([]*Slide, error) {
	if e.loadedTypes[0] {
		return e.Slides, nil
	}
	return nil, &NotLoadedError{edge: "slides"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Deck) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case deck.FieldTheme, deck.FieldAssets:
			values[i] = new([]byte)
		case deck.FieldThumbnailReady:
			values[i] = new(sql.NullBool)
		case deck.FieldSchemaVersion, deck.FieldVersion:
			values[i] = new(sql.NullInt64)
		case deck.FieldSlug, deck.FieldTitle, deck.FieldDescription, deck.FieldTemplateModel, deck.FieldSessionID, deck.FieldSourceSlug:
			values[i] = new(sql.NullString)
		case deck.FieldCreatedAt, deck.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case deck.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Deck fields.
func (_m *Deck) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case deck.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case deck.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case deck.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case deck.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case deck.FieldSchemaVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field schema_version", values[i])
			} else if value.Valid {
				_m.SchemaVersion = int(value.Int64)
			}
		case deck.FieldTheme:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field theme", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Theme); err != nil {
					return fmt.Errorf("unmarshal field theme: %w", err)
				}
			}
		case deck.FieldAssets:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field assets", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Assets); err != nil {
					return fmt.Errorf("unmarshal field assets: %w", err)
				}
			}
		case deck.FieldTemplateModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field template_model", values[i])
			} else if value.Valid {
				_m.TemplateModel = value.String
			}
		case deck.FieldThumbnailReady:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnail_ready", values[i])
			} else if value.Valid {
				_m.ThumbnailReady = value.Bool
			}
		case deck.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case deck.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case deck.FieldSourceSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_slug", values[i])
			} else if value.Valid {
				_m.SourceSlug = value.String
			}
		case deck.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case deck.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Deck.
// This includes values selected through modifiers, order, etc.
func (_m *Deck) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySlides queries the "slides" edge of the Deck entity.
func (_m *Deck) QuerySlides() *SlideQuery {
	return NewDeckClient(_m.config).QuerySlides(_m)
}

// Update returns a builder for updating this Deck.
// Note that you need to call Deck.Unwrap() before calling this method if this Deck
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Deck) Update() *DeckUpdateOne {
	return NewDeckClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Deck entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Deck) Unwrap() *Deck {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("personal: Deck is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Deck) String() string {
	var builder strings.Builder
	builder.WriteString("Deck(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("schema_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.SchemaVersion))
	builder.WriteString(", ")
	builder.WriteString("theme=")
	builder.WriteString(fmt.Sprintf("%v", _m.Theme))
	builder.WriteString(", ")
	builder.WriteString("assets=")
	builder.WriteString(fmt.Sprintf("%v", _m.Assets))
	builder.WriteString(", ")
	builder.WriteString("template_model=")
	builder.WriteString(_m.TemplateModel)
	builder.WriteString(", ")
	builder.WriteString("thumbnail_ready=")
	builder.WriteString(fmt.Sprintf("%v", _m.ThumbnailReady))
	builder.WriteString(", ")
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("source_slug=")
	builder.WriteString(_m.SourceSlug)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Decks is a parsable slice of Deck.
type Decks []*Deck
