// Code generated by ent, DO NOT EDIT.

package personal

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SAP/astonish/ent/personal/deck"
	"github.com/SAP/astonish/ent/personal/slide"
	"github.com/google/uuid"
)

// Slide is the model entity for the Slide schema.
type Slide struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Position holds the value of the "position" field.
	Position int `json:"position,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// SchemaVersion holds the value of the "schema_version" field.
	SchemaVersion int `json:"schema_version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SlideQuery when eager-loading is set.
	Edges        SlideEdges `json:"edges"`
	deck_slides  *uuid.UUID
	selectValues sql.SelectValues
}

// SlideEdges holds the relations/edges for other nodes in the graph.
type SlideEdges struct {
	// Deck holds the value of the deck edge.
	Deck *Deck `json:"deck,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DeckOrErr returns the Deck value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SlideEdges) DeckOrErr() (*Deck, error) {
	if e.Deck != nil {
		return e.Deck, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: deck.Label}
	}
	return nil, &NotLoadedError{edge: "deck"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Slide) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case slide.FieldPosition, slide.FieldSchemaVersion:
			values[i] = new(sql.NullInt64)
		case slide.FieldTitle, slide.FieldContent, slide.FieldNotes:
			values[i] = new(sql.NullString)
		case slide.FieldCreatedAt, slide.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case slide.FieldID:
			values[i] = new(uuid.UUID)
		case slide.ForeignKeys[0]: // deck_slides
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Slide fields.
func (_m *Slide) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case slide.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case slide.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		case slide.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case slide.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case slide.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case slide.FieldSchemaVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field schema_version", values[i])
			} else if value.Valid {
				_m.SchemaVersion = int(value.Int64)
			}
		case slide.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case slide.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case slide.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field deck_slides", values[i])
			} else if value.Valid {
				_m.deck_slides = new(uuid.UUID)
				*_m.deck_slides = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Slide.
// This includes values selected through modifiers, order, etc.
func (_m *Slide) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDeck queries the "deck" edge of the Slide entity.
func (_m *Slide) QueryDeck() *DeckQuery {
	return NewSlideClient(_m.config).QueryDeck(_m)
}

// Update returns a builder for updating this Slide.
// Note that you need to call Slide.Unwrap() before calling this method if this Slide
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Slide) Update() *SlideUpdateOne {
	return NewSlideClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Slide entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Slide) Unwrap() *Slide {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("personal: Slide is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Slide) String() string {
	var builder strings.Builder
	builder.WriteString("Slide(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("schema_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.SchemaVersion))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Slides is a parsable slice of Slide.
type Slides []*Slide
