// Code generated by ent, DO NOT EDIT.

package personal

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/personal/deck"
	"github.com/SAP/astonish/ent/personal/slide"
	"github.com/google/uuid"
)

// SlideCreate is the builder for creating a Slide entity.
type SlideCreate struct {
	config
	mutation *SlideMutation
	hooks    []Hook
}

// SetPosition sets the "position" field.
func (_c *SlideCreate) SetPosition(v int) *SlideCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *SlideCreate) SetTitle(v string) *SlideCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *SlideCreate) SetNillableTitle(v *string) *SlideCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *SlideCreate) SetContent(v string) *SlideCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *SlideCreate) SetNotes(v string) *SlideCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *SlideCreate) SetNillableNotes(v *string) *SlideCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetThumbnailRef sets the "thumbnail_ref" field.
func (_c *SlideCreate) SetThumbnailRef(v string) *SlideCreate {
	_c.mutation.SetThumbnailRef(v)
	return _c
}

// SetNillableThumbnailRef sets the "thumbnail_ref" field if the given value is not nil.
func (_c *SlideCreate) SetNillableThumbnailRef(v *string) *SlideCreate {
	if v != nil {
		_c.SetThumbnailRef(*v)
	}
	return _c
}

// SetSchemaVersion sets the "schema_version" field.
func (_c *SlideCreate) SetSchemaVersion(v int) *SlideCreate {
	_c.mutation.SetSchemaVersion(v)
	return _c
}

// SetNillableSchemaVersion sets the "schema_version" field if the given value is not nil.
func (_c *SlideCreate) SetNillableSchemaVersion(v *int) *SlideCreate {
	if v != nil {
		_c.SetSchemaVersion(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SlideCreate) SetCreatedAt(v time.Time) *SlideCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SlideCreate) SetNillableCreatedAt(v *time.Time) *SlideCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SlideCreate) SetUpdatedAt(v time.Time) *SlideCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SlideCreate) SetNillableUpdatedAt(v *time.Time) *SlideCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SlideCreate) SetID(v uuid.UUID) *SlideCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SlideCreate) SetNillableID(v *uuid.UUID) *SlideCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetDeckID sets the "deck" edge to the Deck entity by ID.
func (_c *SlideCreate) SetDeckID(id uuid.UUID) *SlideCreate {
	_c.mutation.SetDeckID(id)
	return _c
}

// SetDeck sets the "deck" edge to the Deck entity.
func (_c *SlideCreate) SetDeck(v *Deck) *SlideCreate {
	return _c.SetDeckID(v.ID)
}

// Mutation returns the SlideMutation object of the builder.
func (_c *SlideCreate) Mutation() *SlideMutation {
	return _c.mutation
}

// Save creates the Slide in the database.
func (_c *SlideCreate) Save(ctx context.Context) (*Slide, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SlideCreate) SaveX(ctx context.Context) *Slide {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SlideCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SlideCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SlideCreate) defaults() {
	if _, ok := _c.mutation.Title(); !ok {
		v := slide.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := slide.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.ThumbnailRef(); !ok {
		v := slide.DefaultThumbnailRef
		_c.mutation.SetThumbnailRef(v)
	}
	if _, ok := _c.mutation.SchemaVersion(); !ok {
		v := slide.DefaultSchemaVersion
		_c.mutation.SetSchemaVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := slide.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := slide.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := slide.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SlideCreate) check() error {
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`personal: missing required field "Slide.position"`)}
	}
	if v, ok := _c.mutation.Position(); ok {
		if err := slide.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`personal: validator failed for field "Slide.position": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`personal: missing required field "Slide.title"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`personal: missing required field "Slide.content"`)}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`personal: missing required field "Slide.notes"`)}
	}
	if _, ok := _c.mutation.ThumbnailRef(); !ok {
		return &ValidationError{Name: "thumbnail_ref", err: errors.New(`personal: missing required field "Slide.thumbnail_ref"`)}
	}
	if _, ok := _c.mutation.SchemaVersion(); !ok {
		return &ValidationError{Name: "schema_version", err: errors.New(`personal: missing required field "Slide.schema_version"`)}
	}
	switch _c.driver.Dialect() {
	case dialect.MySQL, dialect.SQLite:
		if _, ok := _c.mutation.CreatedAt(); !ok {
			return &ValidationError{Name: "created_at", err: errors.New(`personal: missing required field "Slide.created_at"`)}
		}
	}
	switch _c.driver.Dialect() {
	case dialect.MySQL, dialect.SQLite:
		if _, ok := _c.mutation.UpdatedAt(); !ok {
			return &ValidationError{Name: "updated_at", err: errors.New(`personal: missing required field "Slide.updated_at"`)}
		}
	}
	if len(_c.mutation.DeckIDs()) == 0 {
		return &ValidationError{Name: "deck", err: errors.New(`personal: missing required edge "Slide.deck"`)}
	}
	return nil
}

func (_c *SlideCreate) sqlSave(ctx context.Context) (*Slide, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SlideCreate) createSpec() (*Slide, *sqlgraph.CreateSpec) {
	var (
		_node = &Slide{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(slide.Table, sqlgraph.NewFieldSpec(slide.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(slide.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(slide.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(slide.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(slide.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.ThumbnailRef(); ok {
		_spec.SetField(slide.FieldThumbnailRef, field.TypeString, value)
		_node.ThumbnailRef = value
	}
	if value, ok := _c.mutation.SchemaVersion(); ok {
		_spec.SetField(slide.FieldSchemaVersion, field.TypeInt, value)
		_node.SchemaVersion = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(slide.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(slide.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.DeckIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   slide.DeckTable,
			Columns: []string{slide.DeckColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deck.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.deck_slides = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SlideCreateBulk is the builder for creating many Slide entities in bulk.
type SlideCreateBulk struct {
	config
	err      error
	builders []*SlideCreate
}

// Save creates the Slide entities in the database.
func (_c *SlideCreateBulk) Save(ctx context.Context) ([]*Slide, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Slide, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SlideMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SlideCreateBulk) SaveX(ctx context.Context) []*Slide {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SlideCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SlideCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
