// Code generated by ent, DO NOT EDIT.

package orgslidetemplate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/SAP/astonish/ent/org/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldDescription, v))
}

// SchemaVersion applies equality check predicate on the "schema_version" field. It's identical to SchemaVersionEQ.
func SchemaVersion(v int) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldSchemaVersion, v))
}

// Skin applies equality check predicate on the "skin" field. It's identical to SkinEQ.
func Skin(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldSkin, v))
}

// TemplateModel applies equality check predicate on the "template_model" field. It's identical to TemplateModelEQ.
func TemplateModel(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldTemplateModel, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldContainsFold(FieldName, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldContainsFold(FieldLabel, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldContainsFold(FieldDescription, v))
}

// SchemaVersionEQ applies the EQ predicate on the "schema_version" field.
func SchemaVersionEQ(v int) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldSchemaVersion, v))
}

// SchemaVersionNEQ applies the NEQ predicate on the "schema_version" field.
func SchemaVersionNEQ(v int) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNEQ(FieldSchemaVersion, v))
}

// SchemaVersionIn applies the In predicate on the "schema_version" field.
func SchemaVersionIn(vs ...int) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIn(FieldSchemaVersion, vs...))
}

// SchemaVersionNotIn applies the NotIn predicate on the "schema_version" field.
func SchemaVersionNotIn(vs ...int) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotIn(FieldSchemaVersion, vs...))
}

// SchemaVersionGT applies the GT predicate on the "schema_version" field.
func SchemaVersionGT(v int) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGT(FieldSchemaVersion, v))
}

// SchemaVersionGTE applies the GTE predicate on the "schema_version" field.
func SchemaVersionGTE(v int) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGTE(FieldSchemaVersion, v))
}

// SchemaVersionLT applies the LT predicate on the "schema_version" field.
func SchemaVersionLT(v int) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLT(FieldSchemaVersion, v))
}

// SchemaVersionLTE applies the LTE predicate on the "schema_version" field.
func SchemaVersionLTE(v int) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLTE(FieldSchemaVersion, v))
}

// SkinEQ applies the EQ predicate on the "skin" field.
func SkinEQ(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldSkin, v))
}

// SkinNEQ applies the NEQ predicate on the "skin" field.
func SkinNEQ(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNEQ(FieldSkin, v))
}

// SkinIn applies the In predicate on the "skin" field.
func SkinIn(vs ...string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIn(FieldSkin, vs...))
}

// SkinNotIn applies the NotIn predicate on the "skin" field.
func SkinNotIn(vs ...string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotIn(FieldSkin, vs...))
}

// SkinGT applies the GT predicate on the "skin" field.
func SkinGT(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGT(FieldSkin, v))
}

// SkinGTE applies the GTE predicate on the "skin" field.
func SkinGTE(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGTE(FieldSkin, v))
}

// SkinLT applies the LT predicate on the "skin" field.
func SkinLT(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLT(FieldSkin, v))
}

// SkinLTE applies the LTE predicate on the "skin" field.
func SkinLTE(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLTE(FieldSkin, v))
}

// SkinContains applies the Contains predicate on the "skin" field.
func SkinContains(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldContains(FieldSkin, v))
}

// SkinHasPrefix applies the HasPrefix predicate on the "skin" field.
func SkinHasPrefix(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldHasPrefix(FieldSkin, v))
}

// SkinHasSuffix applies the HasSuffix predicate on the "skin" field.
func SkinHasSuffix(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldHasSuffix(FieldSkin, v))
}

// SkinEqualFold applies the EqualFold predicate on the "skin" field.
func SkinEqualFold(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEqualFold(FieldSkin, v))
}

// SkinContainsFold applies the ContainsFold predicate on the "skin" field.
func SkinContainsFold(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldContainsFold(FieldSkin, v))
}

// TokensIsNil applies the IsNil predicate on the "tokens" field.
func TokensIsNil() predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIsNull(FieldTokens))
}

// TokensNotNil applies the NotNil predicate on the "tokens" field.
func TokensNotNil() predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotNull(FieldTokens))
}

// AssetsIsNil applies the IsNil predicate on the "assets" field.
func AssetsIsNil() predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIsNull(FieldAssets))
}

// AssetsNotNil applies the NotNil predicate on the "assets" field.
func AssetsNotNil() predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotNull(FieldAssets))
}

// PalettesIsNil applies the IsNil predicate on the "palettes" field.
func PalettesIsNil() predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIsNull(FieldPalettes))
}

// PalettesNotNil applies the NotNil predicate on the "palettes" field.
func PalettesNotNil() predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotNull(FieldPalettes))
}

// ArchetypesIsNil applies the IsNil predicate on the "archetypes" field.
func ArchetypesIsNil() predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIsNull(FieldArchetypes))
}

// ArchetypesNotNil applies the NotNil predicate on the "archetypes" field.
func ArchetypesNotNil() predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotNull(FieldArchetypes))
}

// TemplateModelEQ applies the EQ predicate on the "template_model" field.
func TemplateModelEQ(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldTemplateModel, v))
}

// TemplateModelNEQ applies the NEQ predicate on the "template_model" field.
func TemplateModelNEQ(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNEQ(FieldTemplateModel, v))
}

// TemplateModelIn applies the In predicate on the "template_model" field.
func TemplateModelIn(vs ...string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIn(FieldTemplateModel, vs...))
}

// TemplateModelNotIn applies the NotIn predicate on the "template_model" field.
func TemplateModelNotIn(vs ...string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotIn(FieldTemplateModel, vs...))
}

// TemplateModelGT applies the GT predicate on the "template_model" field.
func TemplateModelGT(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGT(FieldTemplateModel, v))
}

// TemplateModelGTE applies the GTE predicate on the "template_model" field.
func TemplateModelGTE(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGTE(FieldTemplateModel, v))
}

// TemplateModelLT applies the LT predicate on the "template_model" field.
func TemplateModelLT(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLT(FieldTemplateModel, v))
}

// TemplateModelLTE applies the LTE predicate on the "template_model" field.
func TemplateModelLTE(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLTE(FieldTemplateModel, v))
}

// TemplateModelContains applies the Contains predicate on the "template_model" field.
func TemplateModelContains(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldContains(FieldTemplateModel, v))
}

// TemplateModelHasPrefix applies the HasPrefix predicate on the "template_model" field.
func TemplateModelHasPrefix(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldHasPrefix(FieldTemplateModel, v))
}

// TemplateModelHasSuffix applies the HasSuffix predicate on the "template_model" field.
func TemplateModelHasSuffix(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldHasSuffix(FieldTemplateModel, v))
}

// TemplateModelIsNil applies the IsNil predicate on the "template_model" field.
func TemplateModelIsNil() predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIsNull(FieldTemplateModel))
}

// TemplateModelNotNil applies the NotNil predicate on the "template_model" field.
func TemplateModelNotNil() predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotNull(FieldTemplateModel))
}

// TemplateModelEqualFold applies the EqualFold predicate on the "template_model" field.
func TemplateModelEqualFold(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEqualFold(FieldTemplateModel, v))
}

// TemplateModelContainsFold applies the ContainsFold predicate on the "template_model" field.
func TemplateModelContainsFold(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldContainsFold(FieldTemplateModel, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldContainsFold(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OrgSlideTemplate) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OrgSlideTemplate) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OrgSlideTemplate) predicate.OrgSlideTemplate {
	return predicate.OrgSlideTemplate(sql.NotPredicates(p))
}
