// Code generated by ent, DO NOT EDIT.

package platform

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/platform/oauthsigningkey"
	"github.com/SAP/astonish/ent/platform/predicate"
)

// OAuthSigningKeyUpdate is the builder for updating OAuthSigningKey entities.
type OAuthSigningKeyUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthSigningKeyMutation
}

// Where appends a list predicates to the OAuthSigningKeyUpdate builder.
func (_u *OAuthSigningKeyUpdate) Where(ps ...predicate.OAuthSigningKey) *OAuthSigningKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKeyID sets the "key_id" field.
func (_u *OAuthSigningKeyUpdate) SetKeyID(v string) *OAuthSigningKeyUpdate {
	_u.mutation.SetKeyID(v)
	return _u
}

// SetNillableKeyID sets the "key_id" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdate) SetNillableKeyID(v *string) *OAuthSigningKeyUpdate {
	if v != nil {
		_u.SetKeyID(*v)
	}
	return _u
}

// SetAlgorithm sets the "algorithm" field.
func (_u *OAuthSigningKeyUpdate) SetAlgorithm(v string) *OAuthSigningKeyUpdate {
	_u.mutation.SetAlgorithm(v)
	return _u
}

// SetNillableAlgorithm sets the "algorithm" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdate) SetNillableAlgorithm(v *string) *OAuthSigningKeyUpdate {
	if v != nil {
		_u.SetAlgorithm(*v)
	}
	return _u
}

// SetPublicJwk sets the "public_jwk" field.
func (_u *OAuthSigningKeyUpdate) SetPublicJwk(v map[string]interface{}) *OAuthSigningKeyUpdate {
	_u.mutation.SetPublicJwk(v)
	return _u
}

// SetEncryptedPrivateKey sets the "encrypted_private_key" field.
func (_u *OAuthSigningKeyUpdate) SetEncryptedPrivateKey(v []byte) *OAuthSigningKeyUpdate {
	_u.mutation.SetEncryptedPrivateKey(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *OAuthSigningKeyUpdate) SetStatus(v oauthsigningkey.Status) *OAuthSigningKeyUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdate) SetNillableStatus(v *oauthsigningkey.Status) *OAuthSigningKeyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotAfter sets the "not_after" field.
func (_u *OAuthSigningKeyUpdate) SetNotAfter(v time.Time) *OAuthSigningKeyUpdate {
	_u.mutation.SetNotAfter(v)
	return _u
}

// SetNillableNotAfter sets the "not_after" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdate) SetNillableNotAfter(v *time.Time) *OAuthSigningKeyUpdate {
	if v != nil {
		_u.SetNotAfter(*v)
	}
	return _u
}

// ClearNotAfter clears the value of the "not_after" field.
func (_u *OAuthSigningKeyUpdate) ClearNotAfter() *OAuthSigningKeyUpdate {
	_u.mutation.ClearNotAfter()
	return _u
}

// Mutation returns the OAuthSigningKeyMutation object of the builder.
func (_u *OAuthSigningKeyUpdate) Mutation() *OAuthSigningKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthSigningKeyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthSigningKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthSigningKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthSigningKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthSigningKeyUpdate) check() error {
	if v, ok := _u.mutation.KeyID(); ok {
		if err := oauthsigningkey.KeyIDValidator(v); err != nil {
			return &ValidationError{Name: "key_id", err: fmt.Errorf(`platform: validator failed for field "OAuthSigningKey.key_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Algorithm(); ok {
		if err := oauthsigningkey.AlgorithmValidator(v); err != nil {
			return &ValidationError{Name: "algorithm", err: fmt.Errorf(`platform: validator failed for field "OAuthSigningKey.algorithm": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EncryptedPrivateKey(); ok {
		if err := oauthsigningkey.EncryptedPrivateKeyValidator(v); err != nil {
			return &ValidationError{Name: "encrypted_private_key", err: fmt.Errorf(`platform: validator failed for field "OAuthSigningKey.encrypted_private_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := oauthsigningkey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`platform: validator failed for field "OAuthSigningKey.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthSigningKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthsigningkey.Table, oauthsigningkey.Columns, sqlgraph.NewFieldSpec(oauthsigningkey.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.KeyID(); ok {
		_spec.SetField(oauthsigningkey.FieldKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Algorithm(); ok {
		_spec.SetField(oauthsigningkey.FieldAlgorithm, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicJwk(); ok {
		_spec.SetField(oauthsigningkey.FieldPublicJwk, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.EncryptedPrivateKey(); ok {
		_spec.SetField(oauthsigningkey.FieldEncryptedPrivateKey, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(oauthsigningkey.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NotAfter(); ok {
		_spec.SetField(oauthsigningkey.FieldNotAfter, field.TypeTime, value)
	}
	if _u.mutation.NotAfterCleared() {
		_spec.ClearField(oauthsigningkey.FieldNotAfter, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthsigningkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthSigningKeyUpdateOne is the builder for updating a single OAuthSigningKey entity.
type OAuthSigningKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthSigningKeyMutation
}

// SetKeyID sets the "key_id" field.
func (_u *OAuthSigningKeyUpdateOne) SetKeyID(v string) *OAuthSigningKeyUpdateOne {
	_u.mutation.SetKeyID(v)
	return _u
}

// SetNillableKeyID sets the "key_id" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdateOne) SetNillableKeyID(v *string) *OAuthSigningKeyUpdateOne {
	if v != nil {
		_u.SetKeyID(*v)
	}
	return _u
}

// SetAlgorithm sets the "algorithm" field.
func (_u *OAuthSigningKeyUpdateOne) SetAlgorithm(v string) *OAuthSigningKeyUpdateOne {
	_u.mutation.SetAlgorithm(v)
	return _u
}

// SetNillableAlgorithm sets the "algorithm" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdateOne) SetNillableAlgorithm(v *string) *OAuthSigningKeyUpdateOne {
	if v != nil {
		_u.SetAlgorithm(*v)
	}
	return _u
}

// SetPublicJwk sets the "public_jwk" field.
func (_u *OAuthSigningKeyUpdateOne) SetPublicJwk(v map[string]interface{}) *OAuthSigningKeyUpdateOne {
	_u.mutation.SetPublicJwk(v)
	return _u
}

// SetEncryptedPrivateKey sets the "encrypted_private_key" field.
func (_u *OAuthSigningKeyUpdateOne) SetEncryptedPrivateKey(v []byte) *OAuthSigningKeyUpdateOne {
	_u.mutation.SetEncryptedPrivateKey(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *OAuthSigningKeyUpdateOne) SetStatus(v oauthsigningkey.Status) *OAuthSigningKeyUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdateOne) SetNillableStatus(v *oauthsigningkey.Status) *OAuthSigningKeyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotAfter sets the "not_after" field.
func (_u *OAuthSigningKeyUpdateOne) SetNotAfter(v time.Time) *OAuthSigningKeyUpdateOne {
	_u.mutation.SetNotAfter(v)
	return _u
}

// SetNillableNotAfter sets the "not_after" field if the given value is not nil.
func (_u *OAuthSigningKeyUpdateOne) SetNillableNotAfter(v *time.Time) *OAuthSigningKeyUpdateOne {
	if v != nil {
		_u.SetNotAfter(*v)
	}
	return _u
}

// ClearNotAfter clears the value of the "not_after" field.
func (_u *OAuthSigningKeyUpdateOne) ClearNotAfter() *OAuthSigningKeyUpdateOne {
	_u.mutation.ClearNotAfter()
	return _u
}

// Mutation returns the OAuthSigningKeyMutation object of the builder.
func (_u *OAuthSigningKeyUpdateOne) Mutation() *OAuthSigningKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthSigningKeyUpdate builder.
func (_u *OAuthSigningKeyUpdateOne) Where(ps ...predicate.OAuthSigningKey) *OAuthSigningKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthSigningKeyUpdateOne) Select(field string, fields ...string) *OAuthSigningKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthSigningKey entity.
func (_u *OAuthSigningKeyUpdateOne) Save(ctx context.Context) (*OAuthSigningKey, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthSigningKeyUpdateOne) SaveX(ctx context.Context) *OAuthSigningKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthSigningKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthSigningKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthSigningKeyUpdateOne) check() error {
	if v, ok := _u.mutation.KeyID(); ok {
		if err := oauthsigningkey.KeyIDValidator(v); err != nil {
			return &ValidationError{Name: "key_id", err: fmt.Errorf(`platform: validator failed for field "OAuthSigningKey.key_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Algorithm(); ok {
		if err := oauthsigningkey.AlgorithmValidator(v); err != nil {
			return &ValidationError{Name: "algorithm", err: fmt.Errorf(`platform: validator failed for field "OAuthSigningKey.algorithm": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EncryptedPrivateKey(); ok {
		if err := oauthsigningkey.EncryptedPrivateKeyValidator(v); err != nil {
			return &ValidationError{Name: "encrypted_private_key", err: fmt.Errorf(`platform: validator failed for field "OAuthSigningKey.encrypted_private_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := oauthsigningkey.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`platform: validator failed for field "OAuthSigningKey.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthSigningKeyUpdateOne) sqlSave(ctx context.Context) (_node *OAuthSigningKey, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthsigningkey.Table, oauthsigningkey.Columns, sqlgraph.NewFieldSpec(oauthsigningkey.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`platform: missing "OAuthSigningKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthsigningkey.FieldID)
		for _, f := range fields {
			if !oauthsigningkey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("platform: invalid field %q for query", f)}
			}
			if f != oauthsigningkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.KeyID(); ok {
		_spec.SetField(oauthsigningkey.FieldKeyID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Algorithm(); ok {
		_spec.SetField(oauthsigningkey.FieldAlgorithm, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicJwk(); ok {
		_spec.SetField(oauthsigningkey.FieldPublicJwk, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.EncryptedPrivateKey(); ok {
		_spec.SetField(oauthsigningkey.FieldEncryptedPrivateKey, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(oauthsigningkey.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.NotAfter(); ok {
		_spec.SetField(oauthsigningkey.FieldNotAfter, field.TypeTime, value)
	}
	if _u.mutation.NotAfterCleared() {
		_spec.ClearField(oauthsigningkey.FieldNotAfter, field.TypeTime)
	}
	_node = &OAuthSigningKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthsigningkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
