// Code generated by ent, DO NOT EDIT.

package platform

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SAP/astonish/ent/platform/oauthsigningkey"
	"github.com/google/uuid"
)

// OAuthSigningKey is the model entity for the OAuthSigningKey schema.
type OAuthSigningKey struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// KeyID holds the value of the "key_id" field.
	KeyID string `json:"key_id,omitempty"`
	// Algorithm holds the value of the "algorithm" field.
	Algorithm string `json:"algorithm,omitempty"`
	// PublicJwk holds the value of the "public_jwk" field.
	PublicJwk map[string]interface{} `json:"public_jwk,omitempty"`
	// EncryptedPrivateKey holds the value of the "encrypted_private_key" field.
	EncryptedPrivateKey []byte `json:"encrypted_private_key,omitempty"`
	// Status holds the value of the "status" field.
	Status oauthsigningkey.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// NotAfter holds the value of the "not_after" field.
	NotAfter     *time.Time `json:"not_after,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthSigningKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthsigningkey.FieldPublicJwk, oauthsigningkey.FieldEncryptedPrivateKey:
			values[i] = new([]byte)
		case oauthsigningkey.FieldKeyID, oauthsigningkey.FieldAlgorithm, oauthsigningkey.FieldStatus:
			values[i] = new(sql.NullString)
		case oauthsigningkey.FieldCreatedAt, oauthsigningkey.FieldNotAfter:
			values[i] = new(sql.NullTime)
		case oauthsigningkey.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthSigningKey fields.
func (_m *OAuthSigningKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthsigningkey.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case oauthsigningkey.FieldKeyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key_id", values[i])
			} else if value.Valid {
				_m.KeyID = value.String
			}
		case oauthsigningkey.FieldAlgorithm:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field algorithm", values[i])
			} else if value.Valid {
				_m.Algorithm = value.String
			}
		case oauthsigningkey.FieldPublicJwk:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field public_jwk", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PublicJwk); err != nil {
					return fmt.Errorf("unmarshal field public_jwk: %w", err)
				}
			}
		case oauthsigningkey.FieldEncryptedPrivateKey:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field encrypted_private_key", values[i])
			} else if value != nil {
				_m.EncryptedPrivateKey = *value
			}
		case oauthsigningkey.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = oauthsigningkey.Status(value.String)
			}
		case oauthsigningkey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oauthsigningkey.FieldNotAfter:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field not_after", values[i])
			} else if value.Valid {
				_m.NotAfter = new(time.Time)
				*_m.NotAfter = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthSigningKey.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthSigningKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OAuthSigningKey.
// Note that you need to call OAuthSigningKey.Unwrap() before calling this method if this OAuthSigningKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthSigningKey) Update() *OAuthSigningKeyUpdateOne {
	return NewOAuthSigningKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthSigningKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthSigningKey) Unwrap() *OAuthSigningKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("platform: OAuthSigningKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthSigningKey) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthSigningKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key_id=")
	builder.WriteString(_m.KeyID)
	builder.WriteString(", ")
	builder.WriteString("algorithm=")
	builder.WriteString(_m.Algorithm)
	builder.WriteString(", ")
	builder.WriteString("public_jwk=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicJwk))
	builder.WriteString(", ")
	builder.WriteString("encrypted_private_key=")
	builder.WriteString(fmt.Sprintf("%v", _m.EncryptedPrivateKey))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.NotAfter; v != nil {
		builder.WriteString("not_after=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// OAuthSigningKeys is a parsable slice of OAuthSigningKey.
type OAuthSigningKeys []*OAuthSigningKey
