// Code generated by ent, DO NOT EDIT.

package platform

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/platform/oauthauthorization"
)

// OAuthAuthorizationCreate is the builder for creating a OAuthAuthorization entity.
type OAuthAuthorizationCreate struct {
	config
	mutation *OAuthAuthorizationMutation
	hooks    []Hook
}

// SetClientID sets the "client_id" field.
func (_c *OAuthAuthorizationCreate) SetClientID(v string) *OAuthAuthorizationCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *OAuthAuthorizationCreate) SetRedirectURI(v string) *OAuthAuthorizationCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetCodeChallenge sets the "code_challenge" field.
func (_c *OAuthAuthorizationCreate) SetCodeChallenge(v string) *OAuthAuthorizationCreate {
	_c.mutation.SetCodeChallenge(v)
	return _c
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_c *OAuthAuthorizationCreate) SetCodeChallengeMethod(v string) *OAuthAuthorizationCreate {
	_c.mutation.SetCodeChallengeMethod(v)
	return _c
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_c *OAuthAuthorizationCreate) SetNillableCodeChallengeMethod(v *string) *OAuthAuthorizationCreate {
	if v != nil {
		_c.SetCodeChallengeMethod(*v)
	}
	return _c
}

// SetNonce sets the "nonce" field.
func (_c *OAuthAuthorizationCreate) SetNonce(v string) *OAuthAuthorizationCreate {
	_c.mutation.SetNonce(v)
	return _c
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_c *OAuthAuthorizationCreate) SetNillableNonce(v *string) *OAuthAuthorizationCreate {
	if v != nil {
		_c.SetNonce(*v)
	}
	return _c
}

// SetSubject sets the "subject" field.
func (_c *OAuthAuthorizationCreate) SetSubject(v string) *OAuthAuthorizationCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetActor sets the "actor" field.
func (_c *OAuthAuthorizationCreate) SetActor(v string) *OAuthAuthorizationCreate {
	_c.mutation.SetActor(v)
	return _c
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_c *OAuthAuthorizationCreate) SetNillableActor(v *string) *OAuthAuthorizationCreate {
	if v != nil {
		_c.SetActor(*v)
	}
	return _c
}

// SetOrgID sets the "org_id" field.
func (_c *OAuthAuthorizationCreate) SetOrgID(v string) *OAuthAuthorizationCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetTeamID sets the "team_id" field.
func (_c *OAuthAuthorizationCreate) SetTeamID(v string) *OAuthAuthorizationCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_c *OAuthAuthorizationCreate) SetNillableTeamID(v *string) *OAuthAuthorizationCreate {
	if v != nil {
		_c.SetTeamID(*v)
	}
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OAuthAuthorizationCreate) SetScopes(v []string) *OAuthAuthorizationCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetResources sets the "resources" field.
func (_c *OAuthAuthorizationCreate) SetResources(v []string) *OAuthAuthorizationCreate {
	_c.mutation.SetResources(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthAuthorizationCreate) SetCreatedAt(v time.Time) *OAuthAuthorizationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthAuthorizationCreate) SetNillableCreatedAt(v *time.Time) *OAuthAuthorizationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthAuthorizationCreate) SetExpiresAt(v time.Time) *OAuthAuthorizationCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetConsumedAt sets the "consumed_at" field.
func (_c *OAuthAuthorizationCreate) SetConsumedAt(v time.Time) *OAuthAuthorizationCreate {
	_c.mutation.SetConsumedAt(v)
	return _c
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_c *OAuthAuthorizationCreate) SetNillableConsumedAt(v *time.Time) *OAuthAuthorizationCreate {
	if v != nil {
		_c.SetConsumedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthAuthorizationCreate) SetID(v string) *OAuthAuthorizationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OAuthAuthorizationMutation object of the builder.
func (_c *OAuthAuthorizationCreate) Mutation() *OAuthAuthorizationMutation {
	return _c.mutation
}

// Save creates the OAuthAuthorization in the database.
func (_c *OAuthAuthorizationCreate) Save(ctx context.Context) (*OAuthAuthorization, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthAuthorizationCreate) SaveX(ctx context.Context) *OAuthAuthorization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthAuthorizationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthAuthorizationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthAuthorizationCreate) defaults() {
	if _, ok := _c.mutation.CodeChallengeMethod(); !ok {
		v := oauthauthorization.DefaultCodeChallengeMethod
		_c.mutation.SetCodeChallengeMethod(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthauthorization.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthAuthorizationCreate) check() error {
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`platform: missing required field "OAuthAuthorization.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthauthorization.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`platform: missing required field "OAuthAuthorization.redirect_uri"`)}
	}
	if v, ok := _c.mutation.RedirectURI(); ok {
		if err := oauthauthorization.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.redirect_uri": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CodeChallenge(); !ok {
		return &ValidationError{Name: "code_challenge", err: errors.New(`platform: missing required field "OAuthAuthorization.code_challenge"`)}
	}
	if v, ok := _c.mutation.CodeChallenge(); ok {
		if err := oauthauthorization.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.code_challenge": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CodeChallengeMethod(); !ok {
		return &ValidationError{Name: "code_challenge_method", err: errors.New(`platform: missing required field "OAuthAuthorization.code_challenge_method"`)}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`platform: missing required field "OAuthAuthorization.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := oauthauthorization.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrgID(); !ok {
		return &ValidationError{Name: "org_id", err: errors.New(`platform: missing required field "OAuthAuthorization.org_id"`)}
	}
	if v, ok := _c.mutation.OrgID(); ok {
		if err := oauthauthorization.OrgIDValidator(v); err != nil {
			return &ValidationError{Name: "org_id", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.org_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`platform: missing required field "OAuthAuthorization.scopes"`)}
	}
	if _, ok := _c.mutation.Resources(); !ok {
		return &ValidationError{Name: "resources", err: errors.New(`platform: missing required field "OAuthAuthorization.resources"`)}
	}
	switch _c.driver.Dialect() {
	case dialect.MySQL, dialect.SQLite:
		if _, ok := _c.mutation.CreatedAt(); !ok {
			return &ValidationError{Name: "created_at", err: errors.New(`platform: missing required field "OAuthAuthorization.created_at"`)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`platform: missing required field "OAuthAuthorization.expires_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := oauthauthorization.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.id": %w`, err)}
		}
	}
	return nil
}

func (_c *OAuthAuthorizationCreate) sqlSave(ctx context.Context) (*OAuthAuthorization, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected OAuthAuthorization.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthAuthorizationCreate) createSpec() (*OAuthAuthorization, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthAuthorization{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthauthorization.Table, sqlgraph.NewFieldSpec(oauthauthorization.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthauthorization.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(oauthauthorization.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthauthorization.FieldCodeChallenge, field.TypeString, value)
		_node.CodeChallenge = value
	}
	if value, ok := _c.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oauthauthorization.FieldCodeChallengeMethod, field.TypeString, value)
		_node.CodeChallengeMethod = value
	}
	if value, ok := _c.mutation.Nonce(); ok {
		_spec.SetField(oauthauthorization.FieldNonce, field.TypeString, value)
		_node.Nonce = &value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(oauthauthorization.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Actor(); ok {
		_spec.SetField(oauthauthorization.FieldActor, field.TypeString, value)
		_node.Actor = &value
	}
	if value, ok := _c.mutation.OrgID(); ok {
		_spec.SetField(oauthauthorization.FieldOrgID, field.TypeString, value)
		_node.OrgID = value
	}
	if value, ok := _c.mutation.TeamID(); ok {
		_spec.SetField(oauthauthorization.FieldTeamID, field.TypeString, value)
		_node.TeamID = &value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauthauthorization.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.Resources(); ok {
		_spec.SetField(oauthauthorization.FieldResources, field.TypeJSON, value)
		_node.Resources = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthauthorization.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthauthorization.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.ConsumedAt(); ok {
		_spec.SetField(oauthauthorization.FieldConsumedAt, field.TypeTime, value)
		_node.ConsumedAt = &value
	}
	return _node, _spec
}

// OAuthAuthorizationCreateBulk is the builder for creating many OAuthAuthorization entities in bulk.
type OAuthAuthorizationCreateBulk struct {
	config
	err      error
	builders []*OAuthAuthorizationCreate
}

// Save creates the OAuthAuthorization entities in the database.
func (_c *OAuthAuthorizationCreateBulk) Save(ctx context.Context) ([]*OAuthAuthorization, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthAuthorization, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthAuthorizationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthAuthorizationCreateBulk) SaveX(ctx context.Context) []*OAuthAuthorization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthAuthorizationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthAuthorizationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
