// Code generated by ent, DO NOT EDIT.

package platform

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SAP/astonish/ent/platform/oauthtoken"
)

// OAuthToken is the model entity for the OAuthToken schema.
type OAuthToken struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// FamilyID holds the value of the "family_id" field.
	FamilyID string `json:"family_id,omitempty"`
	// TokenType holds the value of the "token_type" field.
	TokenType oauthtoken.TokenType `json:"token_type,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// Subject holds the value of the "subject" field.
	Subject *string `json:"subject,omitempty"`
	// Actor holds the value of the "actor" field.
	Actor *string `json:"actor,omitempty"`
	// OrgID holds the value of the "org_id" field.
	OrgID string `json:"org_id,omitempty"`
	// TeamID holds the value of the "team_id" field.
	TeamID *string `json:"team_id,omitempty"`
	// Scopes holds the value of the "scopes" field.
	Scopes []string `json:"scopes,omitempty"`
	// Resources holds the value of the "resources" field.
	Resources []string `json:"resources,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
	// ReplacedBy holds the value of the "replaced_by" field.
	ReplacedBy *string `json:"replaced_by,omitempty"`
	// ReplayDetected holds the value of the "replay_detected" field.
	ReplayDetected bool `json:"replay_detected,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthToken) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthtoken.FieldScopes, oauthtoken.FieldResources:
			values[i] = new([]byte)
		case oauthtoken.FieldReplayDetected:
			values[i] = new(sql.NullBool)
		case oauthtoken.FieldID, oauthtoken.FieldFamilyID, oauthtoken.FieldTokenType, oauthtoken.FieldClientID, oauthtoken.FieldSubject, oauthtoken.FieldActor, oauthtoken.FieldOrgID, oauthtoken.FieldTeamID, oauthtoken.FieldReplacedBy:
			values[i] = new(sql.NullString)
		case oauthtoken.FieldCreatedAt, oauthtoken.FieldExpiresAt, oauthtoken.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthToken fields.
func (_m *OAuthToken) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthtoken.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case oauthtoken.FieldFamilyID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field family_id", values[i])
			} else if value.Valid {
				_m.FamilyID = value.String
			}
		case oauthtoken.FieldTokenType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_type", values[i])
			} else if value.Valid {
				_m.TokenType = oauthtoken.TokenType(value.String)
			}
		case oauthtoken.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case oauthtoken.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = new(string)
				*_m.Subject = value.String
			}
		case oauthtoken.FieldActor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor", values[i])
			} else if value.Valid {
				_m.Actor = new(string)
				*_m.Actor = value.String
			}
		case oauthtoken.FieldOrgID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field org_id", values[i])
			} else if value.Valid {
				_m.OrgID = value.String
			}
		case oauthtoken.FieldTeamID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value.Valid {
				_m.TeamID = new(string)
				*_m.TeamID = value.String
			}
		case oauthtoken.FieldScopes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field scopes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Scopes); err != nil {
					return fmt.Errorf("unmarshal field scopes: %w", err)
				}
			}
		case oauthtoken.FieldResources:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field resources", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Resources); err != nil {
					return fmt.Errorf("unmarshal field resources: %w", err)
				}
			}
		case oauthtoken.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oauthtoken.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case oauthtoken.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		case oauthtoken.FieldReplacedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field replaced_by", values[i])
			} else if value.Valid {
				_m.ReplacedBy = new(string)
				*_m.ReplacedBy = value.String
			}
		case oauthtoken.FieldReplayDetected:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field replay_detected", values[i])
			} else if value.Valid {
				_m.ReplayDetected = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthToken.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthToken) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OAuthToken.
// Note that you need to call OAuthToken.Unwrap() before calling this method if this OAuthToken
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthToken) Update() *OAuthTokenUpdateOne {
	return NewOAuthTokenClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthToken entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthToken) Unwrap() *OAuthToken {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("platform: OAuthToken is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthToken) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthToken(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("family_id=")
	builder.WriteString(_m.FamilyID)
	builder.WriteString(", ")
	builder.WriteString("token_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokenType))
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	if v := _m.Subject; v != nil {
		builder.WriteString("subject=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Actor; v != nil {
		builder.WriteString("actor=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("org_id=")
	builder.WriteString(_m.OrgID)
	builder.WriteString(", ")
	if v := _m.TeamID; v != nil {
		builder.WriteString("team_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("scopes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scopes))
	builder.WriteString(", ")
	builder.WriteString("resources=")
	builder.WriteString(fmt.Sprintf("%v", _m.Resources))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ReplacedBy; v != nil {
		builder.WriteString("replaced_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("replay_detected=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReplayDetected))
	builder.WriteByte(')')
	return builder.String()
}

// OAuthTokens is a parsable slice of OAuthToken.
type OAuthTokens []*OAuthToken
