// Code generated by ent, DO NOT EDIT.

package platform

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/platform/oauthauthorization"
	"github.com/SAP/astonish/ent/platform/predicate"
)

// OAuthAuthorizationUpdate is the builder for updating OAuthAuthorization entities.
type OAuthAuthorizationUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthAuthorizationMutation
}

// Where appends a list predicates to the OAuthAuthorizationUpdate builder.
func (_u *OAuthAuthorizationUpdate) Where(ps ...predicate.OAuthAuthorization) *OAuthAuthorizationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthAuthorizationUpdate) SetClientID(v string) *OAuthAuthorizationUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdate) SetNillableClientID(v *string) *OAuthAuthorizationUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthAuthorizationUpdate) SetRedirectURI(v string) *OAuthAuthorizationUpdate {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdate) SetNillableRedirectURI(v *string) *OAuthAuthorizationUpdate {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *OAuthAuthorizationUpdate) SetCodeChallenge(v string) *OAuthAuthorizationUpdate {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdate) SetNillableCodeChallenge(v *string) *OAuthAuthorizationUpdate {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_u *OAuthAuthorizationUpdate) SetCodeChallengeMethod(v string) *OAuthAuthorizationUpdate {
	_u.mutation.SetCodeChallengeMethod(v)
	return _u
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdate) SetNillableCodeChallengeMethod(v *string) *OAuthAuthorizationUpdate {
	if v != nil {
		_u.SetCodeChallengeMethod(*v)
	}
	return _u
}

// SetNonce sets the "nonce" field.
func (_u *OAuthAuthorizationUpdate) SetNonce(v string) *OAuthAuthorizationUpdate {
	_u.mutation.SetNonce(v)
	return _u
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdate) SetNillableNonce(v *string) *OAuthAuthorizationUpdate {
	if v != nil {
		_u.SetNonce(*v)
	}
	return _u
}

// ClearNonce clears the value of the "nonce" field.
func (_u *OAuthAuthorizationUpdate) ClearNonce() *OAuthAuthorizationUpdate {
	_u.mutation.ClearNonce()
	return _u
}

// SetSubject sets the "subject" field.
func (_u *OAuthAuthorizationUpdate) SetSubject(v string) *OAuthAuthorizationUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdate) SetNillableSubject(v *string) *OAuthAuthorizationUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetActor sets the "actor" field.
func (_u *OAuthAuthorizationUpdate) SetActor(v string) *OAuthAuthorizationUpdate {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdate) SetNillableActor(v *string) *OAuthAuthorizationUpdate {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// ClearActor clears the value of the "actor" field.
func (_u *OAuthAuthorizationUpdate) ClearActor() *OAuthAuthorizationUpdate {
	_u.mutation.ClearActor()
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *OAuthAuthorizationUpdate) SetOrgID(v string) *OAuthAuthorizationUpdate {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdate) SetNillableOrgID(v *string) *OAuthAuthorizationUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *OAuthAuthorizationUpdate) SetTeamID(v string) *OAuthAuthorizationUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdate) SetNillableTeamID(v *string) *OAuthAuthorizationUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// ClearTeamID clears the value of the "team_id" field.
func (_u *OAuthAuthorizationUpdate) ClearTeamID() *OAuthAuthorizationUpdate {
	_u.mutation.ClearTeamID()
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthAuthorizationUpdate) SetScopes(v []string) *OAuthAuthorizationUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthAuthorizationUpdate) AppendScopes(v []string) *OAuthAuthorizationUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetResources sets the "resources" field.
func (_u *OAuthAuthorizationUpdate) SetResources(v []string) *OAuthAuthorizationUpdate {
	_u.mutation.SetResources(v)
	return _u
}

// AppendResources appends value to the "resources" field.
func (_u *OAuthAuthorizationUpdate) AppendResources(v []string) *OAuthAuthorizationUpdate {
	_u.mutation.AppendResources(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthAuthorizationUpdate) SetExpiresAt(v time.Time) *OAuthAuthorizationUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdate) SetNillableExpiresAt(v *time.Time) *OAuthAuthorizationUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *OAuthAuthorizationUpdate) SetConsumedAt(v time.Time) *OAuthAuthorizationUpdate {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdate) SetNillableConsumedAt(v *time.Time) *OAuthAuthorizationUpdate {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *OAuthAuthorizationUpdate) ClearConsumedAt() *OAuthAuthorizationUpdate {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the OAuthAuthorizationMutation object of the builder.
func (_u *OAuthAuthorizationUpdate) Mutation() *OAuthAuthorizationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthAuthorizationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAuthorizationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthAuthorizationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAuthorizationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthAuthorizationUpdate) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthauthorization.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := oauthauthorization.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.redirect_uri": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallenge(); ok {
		if err := oauthauthorization.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.code_challenge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := oauthauthorization.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrgID(); ok {
		if err := oauthauthorization.OrgIDValidator(v); err != nil {
			return &ValidationError{Name: "org_id", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.org_id": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthAuthorizationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthauthorization.Table, oauthauthorization.Columns, sqlgraph.NewFieldSpec(oauthauthorization.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthauthorization.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthauthorization.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthauthorization.FieldCodeChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oauthauthorization.FieldCodeChallengeMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(oauthauthorization.FieldNonce, field.TypeString, value)
	}
	if _u.mutation.NonceCleared() {
		_spec.ClearField(oauthauthorization.FieldNonce, field.TypeString)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(oauthauthorization.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(oauthauthorization.FieldActor, field.TypeString, value)
	}
	if _u.mutation.ActorCleared() {
		_spec.ClearField(oauthauthorization.FieldActor, field.TypeString)
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(oauthauthorization.FieldOrgID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TeamID(); ok {
		_spec.SetField(oauthauthorization.FieldTeamID, field.TypeString, value)
	}
	if _u.mutation.TeamIDCleared() {
		_spec.ClearField(oauthauthorization.FieldTeamID, field.TypeString)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthauthorization.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthauthorization.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.Resources(); ok {
		_spec.SetField(oauthauthorization.FieldResources, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResources(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthauthorization.FieldResources, value)
		})
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthauthorization.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(oauthauthorization.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(oauthauthorization.FieldConsumedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthauthorization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthAuthorizationUpdateOne is the builder for updating a single OAuthAuthorization entity.
type OAuthAuthorizationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthAuthorizationMutation
}

// SetClientID sets the "client_id" field.
func (_u *OAuthAuthorizationUpdateOne) SetClientID(v string) *OAuthAuthorizationUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdateOne) SetNillableClientID(v *string) *OAuthAuthorizationUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthAuthorizationUpdateOne) SetRedirectURI(v string) *OAuthAuthorizationUpdateOne {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdateOne) SetNillableRedirectURI(v *string) *OAuthAuthorizationUpdateOne {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *OAuthAuthorizationUpdateOne) SetCodeChallenge(v string) *OAuthAuthorizationUpdateOne {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdateOne) SetNillableCodeChallenge(v *string) *OAuthAuthorizationUpdateOne {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_u *OAuthAuthorizationUpdateOne) SetCodeChallengeMethod(v string) *OAuthAuthorizationUpdateOne {
	_u.mutation.SetCodeChallengeMethod(v)
	return _u
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdateOne) SetNillableCodeChallengeMethod(v *string) *OAuthAuthorizationUpdateOne {
	if v != nil {
		_u.SetCodeChallengeMethod(*v)
	}
	return _u
}

// SetNonce sets the "nonce" field.
func (_u *OAuthAuthorizationUpdateOne) SetNonce(v string) *OAuthAuthorizationUpdateOne {
	_u.mutation.SetNonce(v)
	return _u
}

// SetNillableNonce sets the "nonce" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdateOne) SetNillableNonce(v *string) *OAuthAuthorizationUpdateOne {
	if v != nil {
		_u.SetNonce(*v)
	}
	return _u
}

// ClearNonce clears the value of the "nonce" field.
func (_u *OAuthAuthorizationUpdateOne) ClearNonce() *OAuthAuthorizationUpdateOne {
	_u.mutation.ClearNonce()
	return _u
}

// SetSubject sets the "subject" field.
func (_u *OAuthAuthorizationUpdateOne) SetSubject(v string) *OAuthAuthorizationUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdateOne) SetNillableSubject(v *string) *OAuthAuthorizationUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetActor sets the "actor" field.
func (_u *OAuthAuthorizationUpdateOne) SetActor(v string) *OAuthAuthorizationUpdateOne {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdateOne) SetNillableActor(v *string) *OAuthAuthorizationUpdateOne {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// ClearActor clears the value of the "actor" field.
func (_u *OAuthAuthorizationUpdateOne) ClearActor() *OAuthAuthorizationUpdateOne {
	_u.mutation.ClearActor()
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *OAuthAuthorizationUpdateOne) SetOrgID(v string) *OAuthAuthorizationUpdateOne {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdateOne) SetNillableOrgID(v *string) *OAuthAuthorizationUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *OAuthAuthorizationUpdateOne) SetTeamID(v string) *OAuthAuthorizationUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdateOne) SetNillableTeamID(v *string) *OAuthAuthorizationUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// ClearTeamID clears the value of the "team_id" field.
func (_u *OAuthAuthorizationUpdateOne) ClearTeamID() *OAuthAuthorizationUpdateOne {
	_u.mutation.ClearTeamID()
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthAuthorizationUpdateOne) SetScopes(v []string) *OAuthAuthorizationUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthAuthorizationUpdateOne) AppendScopes(v []string) *OAuthAuthorizationUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetResources sets the "resources" field.
func (_u *OAuthAuthorizationUpdateOne) SetResources(v []string) *OAuthAuthorizationUpdateOne {
	_u.mutation.SetResources(v)
	return _u
}

// AppendResources appends value to the "resources" field.
func (_u *OAuthAuthorizationUpdateOne) AppendResources(v []string) *OAuthAuthorizationUpdateOne {
	_u.mutation.AppendResources(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *OAuthAuthorizationUpdateOne) SetExpiresAt(v time.Time) *OAuthAuthorizationUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdateOne) SetNillableExpiresAt(v *time.Time) *OAuthAuthorizationUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetConsumedAt sets the "consumed_at" field.
func (_u *OAuthAuthorizationUpdateOne) SetConsumedAt(v time.Time) *OAuthAuthorizationUpdateOne {
	_u.mutation.SetConsumedAt(v)
	return _u
}

// SetNillableConsumedAt sets the "consumed_at" field if the given value is not nil.
func (_u *OAuthAuthorizationUpdateOne) SetNillableConsumedAt(v *time.Time) *OAuthAuthorizationUpdateOne {
	if v != nil {
		_u.SetConsumedAt(*v)
	}
	return _u
}

// ClearConsumedAt clears the value of the "consumed_at" field.
func (_u *OAuthAuthorizationUpdateOne) ClearConsumedAt() *OAuthAuthorizationUpdateOne {
	_u.mutation.ClearConsumedAt()
	return _u
}

// Mutation returns the OAuthAuthorizationMutation object of the builder.
func (_u *OAuthAuthorizationUpdateOne) Mutation() *OAuthAuthorizationMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthAuthorizationUpdate builder.
func (_u *OAuthAuthorizationUpdateOne) Where(ps ...predicate.OAuthAuthorization) *OAuthAuthorizationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthAuthorizationUpdateOne) Select(field string, fields ...string) *OAuthAuthorizationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthAuthorization entity.
func (_u *OAuthAuthorizationUpdateOne) Save(ctx context.Context) (*OAuthAuthorization, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthAuthorizationUpdateOne) SaveX(ctx context.Context) *OAuthAuthorization {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthAuthorizationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthAuthorizationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthAuthorizationUpdateOne) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthauthorization.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := oauthauthorization.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.redirect_uri": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CodeChallenge(); ok {
		if err := oauthauthorization.CodeChallengeValidator(v); err != nil {
			return &ValidationError{Name: "code_challenge", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.code_challenge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := oauthauthorization.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrgID(); ok {
		if err := oauthauthorization.OrgIDValidator(v); err != nil {
			return &ValidationError{Name: "org_id", err: fmt.Errorf(`platform: validator failed for field "OAuthAuthorization.org_id": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthAuthorizationUpdateOne) sqlSave(ctx context.Context) (_node *OAuthAuthorization, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthauthorization.Table, oauthauthorization.Columns, sqlgraph.NewFieldSpec(oauthauthorization.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`platform: missing "OAuthAuthorization.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthauthorization.FieldID)
		for _, f := range fields {
			if !oauthauthorization.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("platform: invalid field %q for query", f)}
			}
			if f != oauthauthorization.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthauthorization.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthauthorization.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(oauthauthorization.FieldCodeChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(oauthauthorization.FieldCodeChallengeMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nonce(); ok {
		_spec.SetField(oauthauthorization.FieldNonce, field.TypeString, value)
	}
	if _u.mutation.NonceCleared() {
		_spec.ClearField(oauthauthorization.FieldNonce, field.TypeString)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(oauthauthorization.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(oauthauthorization.FieldActor, field.TypeString, value)
	}
	if _u.mutation.ActorCleared() {
		_spec.ClearField(oauthauthorization.FieldActor, field.TypeString)
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(oauthauthorization.FieldOrgID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TeamID(); ok {
		_spec.SetField(oauthauthorization.FieldTeamID, field.TypeString, value)
	}
	if _u.mutation.TeamIDCleared() {
		_spec.ClearField(oauthauthorization.FieldTeamID, field.TypeString)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthauthorization.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthauthorization.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.Resources(); ok {
		_spec.SetField(oauthauthorization.FieldResources, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResources(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthauthorization.FieldResources, value)
		})
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthauthorization.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ConsumedAt(); ok {
		_spec.SetField(oauthauthorization.FieldConsumedAt, field.TypeTime, value)
	}
	if _u.mutation.ConsumedAtCleared() {
		_spec.ClearField(oauthauthorization.FieldConsumedAt, field.TypeTime)
	}
	_node = &OAuthAuthorization{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthauthorization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
