// Code generated by ent, DO NOT EDIT.

package platform

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/platform/oauthclient"
	"github.com/SAP/astonish/ent/platform/predicate"
	"github.com/google/uuid"
)

// OAuthClientUpdate is the builder for updating OAuthClient entities.
type OAuthClientUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthClientMutation
}

// Where appends a list predicates to the OAuthClientUpdate builder.
func (_u *OAuthClientUpdate) Where(ps ...predicate.OAuthClient) *OAuthClientUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrgID sets the "org_id" field.
func (_u *OAuthClientUpdate) SetOrgID(v uuid.UUID) *OAuthClientUpdate {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableOrgID(v *uuid.UUID) *OAuthClientUpdate {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// ClearOrgID clears the value of the "org_id" field.
func (_u *OAuthClientUpdate) ClearOrgID() *OAuthClientUpdate {
	_u.mutation.ClearOrgID()
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *OAuthClientUpdate) SetTeamID(v string) *OAuthClientUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableTeamID(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// ClearTeamID clears the value of the "team_id" field.
func (_u *OAuthClientUpdate) ClearTeamID() *OAuthClientUpdate {
	_u.mutation.ClearTeamID()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthClientUpdate) SetClientID(v string) *OAuthClientUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableClientID(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *OAuthClientUpdate) SetName(v string) *OAuthClientUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableName(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetClientType sets the "client_type" field.
func (_u *OAuthClientUpdate) SetClientType(v oauthclient.ClientType) *OAuthClientUpdate {
	_u.mutation.SetClientType(v)
	return _u
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableClientType(v *oauthclient.ClientType) *OAuthClientUpdate {
	if v != nil {
		_u.SetClientType(*v)
	}
	return _u
}

// SetSecretHash sets the "secret_hash" field.
func (_u *OAuthClientUpdate) SetSecretHash(v string) *OAuthClientUpdate {
	_u.mutation.SetSecretHash(v)
	return _u
}

// SetNillableSecretHash sets the "secret_hash" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableSecretHash(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetSecretHash(*v)
	}
	return _u
}

// ClearSecretHash clears the value of the "secret_hash" field.
func (_u *OAuthClientUpdate) ClearSecretHash() *OAuthClientUpdate {
	_u.mutation.ClearSecretHash()
	return _u
}

// SetRedirectUris sets the "redirect_uris" field.
func (_u *OAuthClientUpdate) SetRedirectUris(v []string) *OAuthClientUpdate {
	_u.mutation.SetRedirectUris(v)
	return _u
}

// AppendRedirectUris appends value to the "redirect_uris" field.
func (_u *OAuthClientUpdate) AppendRedirectUris(v []string) *OAuthClientUpdate {
	_u.mutation.AppendRedirectUris(v)
	return _u
}

// SetGrantTypes sets the "grant_types" field.
func (_u *OAuthClientUpdate) SetGrantTypes(v []string) *OAuthClientUpdate {
	_u.mutation.SetGrantTypes(v)
	return _u
}

// AppendGrantTypes appends value to the "grant_types" field.
func (_u *OAuthClientUpdate) AppendGrantTypes(v []string) *OAuthClientUpdate {
	_u.mutation.AppendGrantTypes(v)
	return _u
}

// SetResources sets the "resources" field.
func (_u *OAuthClientUpdate) SetResources(v []string) *OAuthClientUpdate {
	_u.mutation.SetResources(v)
	return _u
}

// AppendResources appends value to the "resources" field.
func (_u *OAuthClientUpdate) AppendResources(v []string) *OAuthClientUpdate {
	_u.mutation.AppendResources(v)
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthClientUpdate) SetScopes(v []string) *OAuthClientUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthClientUpdate) AppendScopes(v []string) *OAuthClientUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *OAuthClientUpdate) SetActive(v bool) *OAuthClientUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableActive(v *bool) *OAuthClientUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthClientUpdate) SetUpdatedAt(v time.Time) *OAuthClientUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OAuthClientMutation object of the builder.
func (_u *OAuthClientUpdate) Mutation() *OAuthClientMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthClientUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthClientUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthClientUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthClientUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthClientUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthclient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthClientUpdate) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthclient.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`platform: validator failed for field "OAuthClient.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := oauthclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`platform: validator failed for field "OAuthClient.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientType(); ok {
		if err := oauthclient.ClientTypeValidator(v); err != nil {
			return &ValidationError{Name: "client_type", err: fmt.Errorf(`platform: validator failed for field "OAuthClient.client_type": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthClientUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthclient.Table, oauthclient.Columns, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.OwnerUserIDCleared() {
		_spec.ClearField(oauthclient.FieldOwnerUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(oauthclient.FieldOrgID, field.TypeUUID, value)
	}
	if _u.mutation.OrgIDCleared() {
		_spec.ClearField(oauthclient.FieldOrgID, field.TypeUUID)
	}
	if value, ok := _u.mutation.TeamID(); ok {
		_spec.SetField(oauthclient.FieldTeamID, field.TypeString, value)
	}
	if _u.mutation.TeamIDCleared() {
		_spec.ClearField(oauthclient.FieldTeamID, field.TypeString)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthclient.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(oauthclient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientType(); ok {
		_spec.SetField(oauthclient.FieldClientType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SecretHash(); ok {
		_spec.SetField(oauthclient.FieldSecretHash, field.TypeString, value)
	}
	if _u.mutation.SecretHashCleared() {
		_spec.ClearField(oauthclient.FieldSecretHash, field.TypeString)
	}
	if value, ok := _u.mutation.RedirectUris(); ok {
		_spec.SetField(oauthclient.FieldRedirectUris, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldRedirectUris, value)
		})
	}
	if value, ok := _u.mutation.GrantTypes(); ok {
		_spec.SetField(oauthclient.FieldGrantTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGrantTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldGrantTypes, value)
		})
	}
	if value, ok := _u.mutation.Resources(); ok {
		_spec.SetField(oauthclient.FieldResources, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResources(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldResources, value)
		})
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthclient.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(oauthclient.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthClientUpdateOne is the builder for updating a single OAuthClient entity.
type OAuthClientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthClientMutation
}

// SetOrgID sets the "org_id" field.
func (_u *OAuthClientUpdateOne) SetOrgID(v uuid.UUID) *OAuthClientUpdateOne {
	_u.mutation.SetOrgID(v)
	return _u
}

// SetNillableOrgID sets the "org_id" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableOrgID(v *uuid.UUID) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetOrgID(*v)
	}
	return _u
}

// ClearOrgID clears the value of the "org_id" field.
func (_u *OAuthClientUpdateOne) ClearOrgID() *OAuthClientUpdateOne {
	_u.mutation.ClearOrgID()
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *OAuthClientUpdateOne) SetTeamID(v string) *OAuthClientUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableTeamID(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// ClearTeamID clears the value of the "team_id" field.
func (_u *OAuthClientUpdateOne) ClearTeamID() *OAuthClientUpdateOne {
	_u.mutation.ClearTeamID()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthClientUpdateOne) SetClientID(v string) *OAuthClientUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableClientID(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *OAuthClientUpdateOne) SetName(v string) *OAuthClientUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableName(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetClientType sets the "client_type" field.
func (_u *OAuthClientUpdateOne) SetClientType(v oauthclient.ClientType) *OAuthClientUpdateOne {
	_u.mutation.SetClientType(v)
	return _u
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableClientType(v *oauthclient.ClientType) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetClientType(*v)
	}
	return _u
}

// SetSecretHash sets the "secret_hash" field.
func (_u *OAuthClientUpdateOne) SetSecretHash(v string) *OAuthClientUpdateOne {
	_u.mutation.SetSecretHash(v)
	return _u
}

// SetNillableSecretHash sets the "secret_hash" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableSecretHash(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetSecretHash(*v)
	}
	return _u
}

// ClearSecretHash clears the value of the "secret_hash" field.
func (_u *OAuthClientUpdateOne) ClearSecretHash() *OAuthClientUpdateOne {
	_u.mutation.ClearSecretHash()
	return _u
}

// SetRedirectUris sets the "redirect_uris" field.
func (_u *OAuthClientUpdateOne) SetRedirectUris(v []string) *OAuthClientUpdateOne {
	_u.mutation.SetRedirectUris(v)
	return _u
}

// AppendRedirectUris appends value to the "redirect_uris" field.
func (_u *OAuthClientUpdateOne) AppendRedirectUris(v []string) *OAuthClientUpdateOne {
	_u.mutation.AppendRedirectUris(v)
	return _u
}

// SetGrantTypes sets the "grant_types" field.
func (_u *OAuthClientUpdateOne) SetGrantTypes(v []string) *OAuthClientUpdateOne {
	_u.mutation.SetGrantTypes(v)
	return _u
}

// AppendGrantTypes appends value to the "grant_types" field.
func (_u *OAuthClientUpdateOne) AppendGrantTypes(v []string) *OAuthClientUpdateOne {
	_u.mutation.AppendGrantTypes(v)
	return _u
}

// SetResources sets the "resources" field.
func (_u *OAuthClientUpdateOne) SetResources(v []string) *OAuthClientUpdateOne {
	_u.mutation.SetResources(v)
	return _u
}

// AppendResources appends value to the "resources" field.
func (_u *OAuthClientUpdateOne) AppendResources(v []string) *OAuthClientUpdateOne {
	_u.mutation.AppendResources(v)
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *OAuthClientUpdateOne) SetScopes(v []string) *OAuthClientUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *OAuthClientUpdateOne) AppendScopes(v []string) *OAuthClientUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *OAuthClientUpdateOne) SetActive(v bool) *OAuthClientUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableActive(v *bool) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthClientUpdateOne) SetUpdatedAt(v time.Time) *OAuthClientUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OAuthClientMutation object of the builder.
func (_u *OAuthClientUpdateOne) Mutation() *OAuthClientMutation {
	return _u.mutation
}

// Where appends a list predicates to the OAuthClientUpdate builder.
func (_u *OAuthClientUpdateOne) Where(ps ...predicate.OAuthClient) *OAuthClientUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthClientUpdateOne) Select(field string, fields ...string) *OAuthClientUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthClient entity.
func (_u *OAuthClientUpdateOne) Save(ctx context.Context) (*OAuthClient, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthClientUpdateOne) SaveX(ctx context.Context) *OAuthClient {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthClientUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthClientUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthClientUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthclient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthClientUpdateOne) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthclient.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`platform: validator failed for field "OAuthClient.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := oauthclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`platform: validator failed for field "OAuthClient.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientType(); ok {
		if err := oauthclient.ClientTypeValidator(v); err != nil {
			return &ValidationError{Name: "client_type", err: fmt.Errorf(`platform: validator failed for field "OAuthClient.client_type": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthClientUpdateOne) sqlSave(ctx context.Context) (_node *OAuthClient, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthclient.Table, oauthclient.Columns, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`platform: missing "OAuthClient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthclient.FieldID)
		for _, f := range fields {
			if !oauthclient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("platform: invalid field %q for query", f)}
			}
			if f != oauthclient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.OwnerUserIDCleared() {
		_spec.ClearField(oauthclient.FieldOwnerUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.OrgID(); ok {
		_spec.SetField(oauthclient.FieldOrgID, field.TypeUUID, value)
	}
	if _u.mutation.OrgIDCleared() {
		_spec.ClearField(oauthclient.FieldOrgID, field.TypeUUID)
	}
	if value, ok := _u.mutation.TeamID(); ok {
		_spec.SetField(oauthclient.FieldTeamID, field.TypeString, value)
	}
	if _u.mutation.TeamIDCleared() {
		_spec.ClearField(oauthclient.FieldTeamID, field.TypeString)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthclient.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(oauthclient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientType(); ok {
		_spec.SetField(oauthclient.FieldClientType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SecretHash(); ok {
		_spec.SetField(oauthclient.FieldSecretHash, field.TypeString, value)
	}
	if _u.mutation.SecretHashCleared() {
		_spec.ClearField(oauthclient.FieldSecretHash, field.TypeString)
	}
	if value, ok := _u.mutation.RedirectUris(); ok {
		_spec.SetField(oauthclient.FieldRedirectUris, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldRedirectUris, value)
		})
	}
	if value, ok := _u.mutation.GrantTypes(); ok {
		_spec.SetField(oauthclient.FieldGrantTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGrantTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldGrantTypes, value)
		})
	}
	if value, ok := _u.mutation.Resources(); ok {
		_spec.SetField(oauthclient.FieldResources, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResources(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldResources, value)
		})
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(oauthclient.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, oauthclient.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(oauthclient.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OAuthClient{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
