// Code generated by ent, DO NOT EDIT.

package platform

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/platform/oauthconsent"
	"github.com/google/uuid"
)

// OAuthConsentCreate is the builder for creating a OAuthConsent entity.
type OAuthConsentCreate struct {
	config
	mutation *OAuthConsentMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *OAuthConsentCreate) SetUserID(v uuid.UUID) *OAuthConsentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetOrgID sets the "org_id" field.
func (_c *OAuthConsentCreate) SetOrgID(v uuid.UUID) *OAuthConsentCreate {
	_c.mutation.SetOrgID(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthConsentCreate) SetClientID(v string) *OAuthConsentCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OAuthConsentCreate) SetScopes(v []string) *OAuthConsentCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetResources sets the "resources" field.
func (_c *OAuthConsentCreate) SetResources(v []string) *OAuthConsentCreate {
	_c.mutation.SetResources(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthConsentCreate) SetCreatedAt(v time.Time) *OAuthConsentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthConsentCreate) SetNillableCreatedAt(v *time.Time) *OAuthConsentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthConsentCreate) SetExpiresAt(v time.Time) *OAuthConsentCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *OAuthConsentCreate) SetNillableExpiresAt(v *time.Time) *OAuthConsentCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *OAuthConsentCreate) SetRevokedAt(v time.Time) *OAuthConsentCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *OAuthConsentCreate) SetNillableRevokedAt(v *time.Time) *OAuthConsentCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthConsentCreate) SetID(v uuid.UUID) *OAuthConsentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OAuthConsentCreate) SetNillableID(v *uuid.UUID) *OAuthConsentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the OAuthConsentMutation object of the builder.
func (_c *OAuthConsentCreate) Mutation() *OAuthConsentMutation {
	return _c.mutation
}

// Save creates the OAuthConsent in the database.
func (_c *OAuthConsentCreate) Save(ctx context.Context) (*OAuthConsent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthConsentCreate) SaveX(ctx context.Context) *OAuthConsent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthConsentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthConsentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthConsentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthconsent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := oauthconsent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthConsentCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`platform: missing required field "OAuthConsent.user_id"`)}
	}
	if _, ok := _c.mutation.OrgID(); !ok {
		return &ValidationError{Name: "org_id", err: errors.New(`platform: missing required field "OAuthConsent.org_id"`)}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`platform: missing required field "OAuthConsent.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthconsent.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`platform: validator failed for field "OAuthConsent.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`platform: missing required field "OAuthConsent.scopes"`)}
	}
	if _, ok := _c.mutation.Resources(); !ok {
		return &ValidationError{Name: "resources", err: errors.New(`platform: missing required field "OAuthConsent.resources"`)}
	}
	switch _c.driver.Dialect() {
	case dialect.MySQL, dialect.SQLite:
		if _, ok := _c.mutation.CreatedAt(); !ok {
			return &ValidationError{Name: "created_at", err: errors.New(`platform: missing required field "OAuthConsent.created_at"`)}
		}
	}
	return nil
}

func (_c *OAuthConsentCreate) sqlSave(ctx context.Context) (*OAuthConsent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthConsentCreate) createSpec() (*OAuthConsent, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthConsent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthconsent.Table, sqlgraph.NewFieldSpec(oauthconsent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(oauthconsent.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.OrgID(); ok {
		_spec.SetField(oauthconsent.FieldOrgID, field.TypeUUID, value)
		_node.OrgID = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthconsent.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauthconsent.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.Resources(); ok {
		_spec.SetField(oauthconsent.FieldResources, field.TypeJSON, value)
		_node.Resources = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthconsent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthconsent.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(oauthconsent.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	return _node, _spec
}

// OAuthConsentCreateBulk is the builder for creating many OAuthConsent entities in bulk.
type OAuthConsentCreateBulk struct {
	config
	err      error
	builders []*OAuthConsentCreate
}

// Save creates the OAuthConsent entities in the database.
func (_c *OAuthConsentCreateBulk) Save(ctx context.Context) ([]*OAuthConsent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthConsent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthConsentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthConsentCreateBulk) SaveX(ctx context.Context) []*OAuthConsent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthConsentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthConsentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
