// Code generated by ent, DO NOT EDIT.

package platform

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SAP/astonish/ent/platform/platformslidetemplate"
	"github.com/google/uuid"
)

// PlatformSlideTemplateCreate is the builder for creating a PlatformSlideTemplate entity.
type PlatformSlideTemplateCreate struct {
	config
	mutation *PlatformSlideTemplateMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *PlatformSlideTemplateCreate) SetName(v string) *PlatformSlideTemplateCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetLabel sets the "label" field.
func (_c *PlatformSlideTemplateCreate) SetLabel(v string) *PlatformSlideTemplateCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *PlatformSlideTemplateCreate) SetNillableLabel(v *string) *PlatformSlideTemplateCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *PlatformSlideTemplateCreate) SetDescription(v string) *PlatformSlideTemplateCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PlatformSlideTemplateCreate) SetNillableDescription(v *string) *PlatformSlideTemplateCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetSchemaVersion sets the "schema_version" field.
func (_c *PlatformSlideTemplateCreate) SetSchemaVersion(v int) *PlatformSlideTemplateCreate {
	_c.mutation.SetSchemaVersion(v)
	return _c
}

// SetNillableSchemaVersion sets the "schema_version" field if the given value is not nil.
func (_c *PlatformSlideTemplateCreate) SetNillableSchemaVersion(v *int) *PlatformSlideTemplateCreate {
	if v != nil {
		_c.SetSchemaVersion(*v)
	}
	return _c
}

// SetSkin sets the "skin" field.
func (_c *PlatformSlideTemplateCreate) SetSkin(v string) *PlatformSlideTemplateCreate {
	_c.mutation.SetSkin(v)
	return _c
}

// SetNillableSkin sets the "skin" field if the given value is not nil.
func (_c *PlatformSlideTemplateCreate) SetNillableSkin(v *string) *PlatformSlideTemplateCreate {
	if v != nil {
		_c.SetSkin(*v)
	}
	return _c
}

// SetTokens sets the "tokens" field.
func (_c *PlatformSlideTemplateCreate) SetTokens(v map[string]string) *PlatformSlideTemplateCreate {
	_c.mutation.SetTokens(v)
	return _c
}

// SetAssets sets the "assets" field.
func (_c *PlatformSlideTemplateCreate) SetAssets(v map[string]string) *PlatformSlideTemplateCreate {
	_c.mutation.SetAssets(v)
	return _c
}

// SetPalettes sets the "palettes" field.
func (_c *PlatformSlideTemplateCreate) SetPalettes(v []interface{}) *PlatformSlideTemplateCreate {
	_c.mutation.SetPalettes(v)
	return _c
}

// SetArchetypes sets the "archetypes" field.
func (_c *PlatformSlideTemplateCreate) SetArchetypes(v []interface{}) *PlatformSlideTemplateCreate {
	_c.mutation.SetArchetypes(v)
	return _c
}

// SetTemplateModel sets the "template_model" field.
func (_c *PlatformSlideTemplateCreate) SetTemplateModel(v string) *PlatformSlideTemplateCreate {
	_c.mutation.SetTemplateModel(v)
	return _c
}

// SetNillableTemplateModel sets the "template_model" field if the given value is not nil.
func (_c *PlatformSlideTemplateCreate) SetNillableTemplateModel(v *string) *PlatformSlideTemplateCreate {
	if v != nil {
		_c.SetTemplateModel(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *PlatformSlideTemplateCreate) SetCreatedBy(v string) *PlatformSlideTemplateCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *PlatformSlideTemplateCreate) SetNillableCreatedBy(v *string) *PlatformSlideTemplateCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlatformSlideTemplateCreate) SetCreatedAt(v time.Time) *PlatformSlideTemplateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlatformSlideTemplateCreate) SetNillableCreatedAt(v *time.Time) *PlatformSlideTemplateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlatformSlideTemplateCreate) SetUpdatedAt(v time.Time) *PlatformSlideTemplateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlatformSlideTemplateCreate) SetNillableUpdatedAt(v *time.Time) *PlatformSlideTemplateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PlatformSlideTemplateCreate) SetID(v uuid.UUID) *PlatformSlideTemplateCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PlatformSlideTemplateCreate) SetNillableID(v *uuid.UUID) *PlatformSlideTemplateCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PlatformSlideTemplateMutation object of the builder.
func (_c *PlatformSlideTemplateCreate) Mutation() *PlatformSlideTemplateMutation {
	return _c.mutation
}

// Save creates the PlatformSlideTemplate in the database.
func (_c *PlatformSlideTemplateCreate) Save(ctx context.Context) (*PlatformSlideTemplate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlatformSlideTemplateCreate) SaveX(ctx context.Context) *PlatformSlideTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformSlideTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformSlideTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlatformSlideTemplateCreate) defaults() {
	if _, ok := _c.mutation.Label(); !ok {
		v := platformslidetemplate.DefaultLabel
		_c.mutation.SetLabel(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := platformslidetemplate.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.SchemaVersion(); !ok {
		v := platformslidetemplate.DefaultSchemaVersion
		_c.mutation.SetSchemaVersion(v)
	}
	if _, ok := _c.mutation.Skin(); !ok {
		v := platformslidetemplate.DefaultSkin
		_c.mutation.SetSkin(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := platformslidetemplate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := platformslidetemplate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := platformslidetemplate.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlatformSlideTemplateCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`platform: missing required field "PlatformSlideTemplate.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := platformslidetemplate.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`platform: validator failed for field "PlatformSlideTemplate.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`platform: missing required field "PlatformSlideTemplate.label"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`platform: missing required field "PlatformSlideTemplate.description"`)}
	}
	if _, ok := _c.mutation.SchemaVersion(); !ok {
		return &ValidationError{Name: "schema_version", err: errors.New(`platform: missing required field "PlatformSlideTemplate.schema_version"`)}
	}
	if _, ok := _c.mutation.Skin(); !ok {
		return &ValidationError{Name: "skin", err: errors.New(`platform: missing required field "PlatformSlideTemplate.skin"`)}
	}
	switch _c.driver.Dialect() {
	case dialect.MySQL, dialect.SQLite:
		if _, ok := _c.mutation.CreatedAt(); !ok {
			return &ValidationError{Name: "created_at", err: errors.New(`platform: missing required field "PlatformSlideTemplate.created_at"`)}
		}
	}
	switch _c.driver.Dialect() {
	case dialect.MySQL, dialect.SQLite:
		if _, ok := _c.mutation.UpdatedAt(); !ok {
			return &ValidationError{Name: "updated_at", err: errors.New(`platform: missing required field "PlatformSlideTemplate.updated_at"`)}
		}
	}
	return nil
}

func (_c *PlatformSlideTemplateCreate) sqlSave(ctx context.Context) (*PlatformSlideTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlatformSlideTemplateCreate) createSpec() (*PlatformSlideTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &PlatformSlideTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(platformslidetemplate.Table, sqlgraph.NewFieldSpec(platformslidetemplate.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(platformslidetemplate.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(platformslidetemplate.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(platformslidetemplate.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.SchemaVersion(); ok {
		_spec.SetField(platformslidetemplate.FieldSchemaVersion, field.TypeInt, value)
		_node.SchemaVersion = value
	}
	if value, ok := _c.mutation.Skin(); ok {
		_spec.SetField(platformslidetemplate.FieldSkin, field.TypeString, value)
		_node.Skin = value
	}
	if value, ok := _c.mutation.Tokens(); ok {
		_spec.SetField(platformslidetemplate.FieldTokens, field.TypeJSON, value)
		_node.Tokens = value
	}
	if value, ok := _c.mutation.Assets(); ok {
		_spec.SetField(platformslidetemplate.FieldAssets, field.TypeJSON, value)
		_node.Assets = value
	}
	if value, ok := _c.mutation.Palettes(); ok {
		_spec.SetField(platformslidetemplate.FieldPalettes, field.TypeJSON, value)
		_node.Palettes = value
	}
	if value, ok := _c.mutation.Archetypes(); ok {
		_spec.SetField(platformslidetemplate.FieldArchetypes, field.TypeJSON, value)
		_node.Archetypes = value
	}
	if value, ok := _c.mutation.TemplateModel(); ok {
		_spec.SetField(platformslidetemplate.FieldTemplateModel, field.TypeString, value)
		_node.TemplateModel = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(platformslidetemplate.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(platformslidetemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(platformslidetemplate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PlatformSlideTemplateCreateBulk is the builder for creating many PlatformSlideTemplate entities in bulk.
type PlatformSlideTemplateCreateBulk struct {
	config
	err      error
	builders []*PlatformSlideTemplateCreate
}

// Save creates the PlatformSlideTemplate entities in the database.
func (_c *PlatformSlideTemplateCreateBulk) Save(ctx context.Context) ([]*PlatformSlideTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PlatformSlideTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlatformSlideTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlatformSlideTemplateCreateBulk) SaveX(ctx context.Context) []*PlatformSlideTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformSlideTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformSlideTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
