// Code generated by ent, DO NOT EDIT.

package platform

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SAP/astonish/ent/platform/platformslidetemplate"
	"github.com/google/uuid"
)

// PlatformSlideTemplate is the model entity for the PlatformSlideTemplate schema.
type PlatformSlideTemplate struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// SchemaVersion holds the value of the "schema_version" field.
	SchemaVersion int `json:"schema_version,omitempty"`
	// Skin holds the value of the "skin" field.
	Skin string `json:"skin,omitempty"`
	// Tokens holds the value of the "tokens" field.
	Tokens map[string]string `json:"tokens,omitempty"`
	// Assets holds the value of the "assets" field.
	Assets map[string]string `json:"assets,omitempty"`
	// Palettes holds the value of the "palettes" field.
	Palettes []interface{} `json:"palettes,omitempty"`
	// Archetypes holds the value of the "archetypes" field.
	Archetypes []interface{} `json:"archetypes,omitempty"`
	// TemplateModel holds the value of the "template_model" field.
	TemplateModel string `json:"template_model,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlatformSlideTemplate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case platformslidetemplate.FieldTokens, platformslidetemplate.FieldAssets, platformslidetemplate.FieldPalettes, platformslidetemplate.FieldArchetypes:
			values[i] = new([]byte)
		case platformslidetemplate.FieldSchemaVersion:
			values[i] = new(sql.NullInt64)
		case platformslidetemplate.FieldName, platformslidetemplate.FieldLabel, platformslidetemplate.FieldDescription, platformslidetemplate.FieldSkin, platformslidetemplate.FieldTemplateModel, platformslidetemplate.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case platformslidetemplate.FieldCreatedAt, platformslidetemplate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case platformslidetemplate.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlatformSlideTemplate fields.
func (_m *PlatformSlideTemplate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case platformslidetemplate.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case platformslidetemplate.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case platformslidetemplate.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case platformslidetemplate.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case platformslidetemplate.FieldSchemaVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field schema_version", values[i])
			} else if value.Valid {
				_m.SchemaVersion = int(value.Int64)
			}
		case platformslidetemplate.FieldSkin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field skin", values[i])
			} else if value.Valid {
				_m.Skin = value.String
			}
		case platformslidetemplate.FieldTokens:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tokens", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tokens); err != nil {
					return fmt.Errorf("unmarshal field tokens: %w", err)
				}
			}
		case platformslidetemplate.FieldAssets:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field assets", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Assets); err != nil {
					return fmt.Errorf("unmarshal field assets: %w", err)
				}
			}
		case platformslidetemplate.FieldPalettes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field palettes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Palettes); err != nil {
					return fmt.Errorf("unmarshal field palettes: %w", err)
				}
			}
		case platformslidetemplate.FieldArchetypes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field archetypes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Archetypes); err != nil {
					return fmt.Errorf("unmarshal field archetypes: %w", err)
				}
			}
		case platformslidetemplate.FieldTemplateModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field template_model", values[i])
			} else if value.Valid {
				_m.TemplateModel = value.String
			}
		case platformslidetemplate.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(string)
				*_m.CreatedBy = value.String
			}
		case platformslidetemplate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case platformslidetemplate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlatformSlideTemplate.
// This includes values selected through modifiers, order, etc.
func (_m *PlatformSlideTemplate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PlatformSlideTemplate.
// Note that you need to call PlatformSlideTemplate.Unwrap() before calling this method if this PlatformSlideTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlatformSlideTemplate) Update() *PlatformSlideTemplateUpdateOne {
	return NewPlatformSlideTemplateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlatformSlideTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlatformSlideTemplate) Unwrap() *PlatformSlideTemplate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("platform: PlatformSlideTemplate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlatformSlideTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("PlatformSlideTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("schema_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.SchemaVersion))
	builder.WriteString(", ")
	builder.WriteString("skin=")
	builder.WriteString(_m.Skin)
	builder.WriteString(", ")
	builder.WriteString("tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tokens))
	builder.WriteString(", ")
	builder.WriteString("assets=")
	builder.WriteString(fmt.Sprintf("%v", _m.Assets))
	builder.WriteString(", ")
	builder.WriteString("palettes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Palettes))
	builder.WriteString(", ")
	builder.WriteString("archetypes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Archetypes))
	builder.WriteString(", ")
	builder.WriteString("template_model=")
	builder.WriteString(_m.TemplateModel)
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PlatformSlideTemplates is a parsable slice of PlatformSlideTemplate.
type PlatformSlideTemplates []*PlatformSlideTemplate
