// Code generated by ent, DO NOT EDIT.

package cachediagnostic

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SAP/astonish/ent/team/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLTE(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldSessionID, v))
}

// InvocationID applies equality check predicate on the "invocation_id" field. It's identical to InvocationIDEQ.
func InvocationID(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldInvocationID, v))
}

// Call applies equality check predicate on the "call" field. It's identical to CallEQ.
func Call(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldCall, v))
}

// Data applies equality check predicate on the "data" field. It's identical to DataEQ.
func Data(v []byte) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldData, v))
}

// Round applies equality check predicate on the "round" field. It's identical to RoundEQ.
func Round(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldRound, v))
}

// CacheStablePath applies equality check predicate on the "cache_stable_path" field. It's identical to CacheStablePathEQ.
func CacheStablePath(v bool) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldCacheStablePath, v))
}

// SystemHash applies equality check predicate on the "system_hash" field. It's identical to SystemHashEQ.
func SystemHash(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldSystemHash, v))
}

// SystemChanged applies equality check predicate on the "system_changed" field. It's identical to SystemChangedEQ.
func SystemChanged(v bool) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldSystemChanged, v))
}

// SystemChangedSession applies equality check predicate on the "system_changed_session" field. It's identical to SystemChangedSessionEQ.
func SystemChangedSession(v bool) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldSystemChangedSession, v))
}

// ToolHash applies equality check predicate on the "tool_hash" field. It's identical to ToolHashEQ.
func ToolHash(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldToolHash, v))
}

// ToolCount applies equality check predicate on the "tool_count" field. It's identical to ToolCountEQ.
func ToolCount(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldToolCount, v))
}

// ToolsChanged applies equality check predicate on the "tools_changed" field. It's identical to ToolsChangedEQ.
func ToolsChanged(v bool) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldToolsChanged, v))
}

// ToolsChangedSession applies equality check predicate on the "tools_changed_session" field. It's identical to ToolsChangedSessionEQ.
func ToolsChangedSession(v bool) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldToolsChangedSession, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldCreatedAt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldContainsFold(FieldSessionID, v))
}

// InvocationIDEQ applies the EQ predicate on the "invocation_id" field.
func InvocationIDEQ(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldInvocationID, v))
}

// InvocationIDNEQ applies the NEQ predicate on the "invocation_id" field.
func InvocationIDNEQ(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNEQ(FieldInvocationID, v))
}

// InvocationIDIn applies the In predicate on the "invocation_id" field.
func InvocationIDIn(vs ...string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldIn(FieldInvocationID, vs...))
}

// InvocationIDNotIn applies the NotIn predicate on the "invocation_id" field.
func InvocationIDNotIn(vs ...string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNotIn(FieldInvocationID, vs...))
}

// InvocationIDGT applies the GT predicate on the "invocation_id" field.
func InvocationIDGT(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGT(FieldInvocationID, v))
}

// InvocationIDGTE applies the GTE predicate on the "invocation_id" field.
func InvocationIDGTE(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGTE(FieldInvocationID, v))
}

// InvocationIDLT applies the LT predicate on the "invocation_id" field.
func InvocationIDLT(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLT(FieldInvocationID, v))
}

// InvocationIDLTE applies the LTE predicate on the "invocation_id" field.
func InvocationIDLTE(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLTE(FieldInvocationID, v))
}

// InvocationIDContains applies the Contains predicate on the "invocation_id" field.
func InvocationIDContains(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldContains(FieldInvocationID, v))
}

// InvocationIDHasPrefix applies the HasPrefix predicate on the "invocation_id" field.
func InvocationIDHasPrefix(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldHasPrefix(FieldInvocationID, v))
}

// InvocationIDHasSuffix applies the HasSuffix predicate on the "invocation_id" field.
func InvocationIDHasSuffix(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldHasSuffix(FieldInvocationID, v))
}

// InvocationIDEqualFold applies the EqualFold predicate on the "invocation_id" field.
func InvocationIDEqualFold(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEqualFold(FieldInvocationID, v))
}

// InvocationIDContainsFold applies the ContainsFold predicate on the "invocation_id" field.
func InvocationIDContainsFold(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldContainsFold(FieldInvocationID, v))
}

// CallEQ applies the EQ predicate on the "call" field.
func CallEQ(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldCall, v))
}

// CallNEQ applies the NEQ predicate on the "call" field.
func CallNEQ(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNEQ(FieldCall, v))
}

// CallIn applies the In predicate on the "call" field.
func CallIn(vs ...int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldIn(FieldCall, vs...))
}

// CallNotIn applies the NotIn predicate on the "call" field.
func CallNotIn(vs ...int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNotIn(FieldCall, vs...))
}

// CallGT applies the GT predicate on the "call" field.
func CallGT(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGT(FieldCall, v))
}

// CallGTE applies the GTE predicate on the "call" field.
func CallGTE(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGTE(FieldCall, v))
}

// CallLT applies the LT predicate on the "call" field.
func CallLT(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLT(FieldCall, v))
}

// CallLTE applies the LTE predicate on the "call" field.
func CallLTE(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLTE(FieldCall, v))
}

// DataEQ applies the EQ predicate on the "data" field.
func DataEQ(v []byte) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldData, v))
}

// DataNEQ applies the NEQ predicate on the "data" field.
func DataNEQ(v []byte) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNEQ(FieldData, v))
}

// DataIn applies the In predicate on the "data" field.
func DataIn(vs ...[]byte) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldIn(FieldData, vs...))
}

// DataNotIn applies the NotIn predicate on the "data" field.
func DataNotIn(vs ...[]byte) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNotIn(FieldData, vs...))
}

// DataGT applies the GT predicate on the "data" field.
func DataGT(v []byte) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGT(FieldData, v))
}

// DataGTE applies the GTE predicate on the "data" field.
func DataGTE(v []byte) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGTE(FieldData, v))
}

// DataLT applies the LT predicate on the "data" field.
func DataLT(v []byte) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLT(FieldData, v))
}

// DataLTE applies the LTE predicate on the "data" field.
func DataLTE(v []byte) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLTE(FieldData, v))
}

// DataIsNil applies the IsNil predicate on the "data" field.
func DataIsNil() predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldIsNull(FieldData))
}

// DataNotNil applies the NotNil predicate on the "data" field.
func DataNotNil() predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNotNull(FieldData))
}

// RoundEQ applies the EQ predicate on the "round" field.
func RoundEQ(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldRound, v))
}

// RoundNEQ applies the NEQ predicate on the "round" field.
func RoundNEQ(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNEQ(FieldRound, v))
}

// RoundIn applies the In predicate on the "round" field.
func RoundIn(vs ...int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldIn(FieldRound, vs...))
}

// RoundNotIn applies the NotIn predicate on the "round" field.
func RoundNotIn(vs ...int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNotIn(FieldRound, vs...))
}

// RoundGT applies the GT predicate on the "round" field.
func RoundGT(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGT(FieldRound, v))
}

// RoundGTE applies the GTE predicate on the "round" field.
func RoundGTE(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGTE(FieldRound, v))
}

// RoundLT applies the LT predicate on the "round" field.
func RoundLT(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLT(FieldRound, v))
}

// RoundLTE applies the LTE predicate on the "round" field.
func RoundLTE(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLTE(FieldRound, v))
}

// CacheStablePathEQ applies the EQ predicate on the "cache_stable_path" field.
func CacheStablePathEQ(v bool) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldCacheStablePath, v))
}

// CacheStablePathNEQ applies the NEQ predicate on the "cache_stable_path" field.
func CacheStablePathNEQ(v bool) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNEQ(FieldCacheStablePath, v))
}

// SystemHashEQ applies the EQ predicate on the "system_hash" field.
func SystemHashEQ(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldSystemHash, v))
}

// SystemHashNEQ applies the NEQ predicate on the "system_hash" field.
func SystemHashNEQ(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNEQ(FieldSystemHash, v))
}

// SystemHashIn applies the In predicate on the "system_hash" field.
func SystemHashIn(vs ...string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldIn(FieldSystemHash, vs...))
}

// SystemHashNotIn applies the NotIn predicate on the "system_hash" field.
func SystemHashNotIn(vs ...string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNotIn(FieldSystemHash, vs...))
}

// SystemHashGT applies the GT predicate on the "system_hash" field.
func SystemHashGT(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGT(FieldSystemHash, v))
}

// SystemHashGTE applies the GTE predicate on the "system_hash" field.
func SystemHashGTE(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGTE(FieldSystemHash, v))
}

// SystemHashLT applies the LT predicate on the "system_hash" field.
func SystemHashLT(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLT(FieldSystemHash, v))
}

// SystemHashLTE applies the LTE predicate on the "system_hash" field.
func SystemHashLTE(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLTE(FieldSystemHash, v))
}

// SystemHashContains applies the Contains predicate on the "system_hash" field.
func SystemHashContains(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldContains(FieldSystemHash, v))
}

// SystemHashHasPrefix applies the HasPrefix predicate on the "system_hash" field.
func SystemHashHasPrefix(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldHasPrefix(FieldSystemHash, v))
}

// SystemHashHasSuffix applies the HasSuffix predicate on the "system_hash" field.
func SystemHashHasSuffix(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldHasSuffix(FieldSystemHash, v))
}

// SystemHashEqualFold applies the EqualFold predicate on the "system_hash" field.
func SystemHashEqualFold(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEqualFold(FieldSystemHash, v))
}

// SystemHashContainsFold applies the ContainsFold predicate on the "system_hash" field.
func SystemHashContainsFold(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldContainsFold(FieldSystemHash, v))
}

// SystemChangedEQ applies the EQ predicate on the "system_changed" field.
func SystemChangedEQ(v bool) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldSystemChanged, v))
}

// SystemChangedNEQ applies the NEQ predicate on the "system_changed" field.
func SystemChangedNEQ(v bool) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNEQ(FieldSystemChanged, v))
}

// SystemChangedSessionEQ applies the EQ predicate on the "system_changed_session" field.
func SystemChangedSessionEQ(v bool) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldSystemChangedSession, v))
}

// SystemChangedSessionNEQ applies the NEQ predicate on the "system_changed_session" field.
func SystemChangedSessionNEQ(v bool) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNEQ(FieldSystemChangedSession, v))
}

// ToolHashEQ applies the EQ predicate on the "tool_hash" field.
func ToolHashEQ(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldToolHash, v))
}

// ToolHashNEQ applies the NEQ predicate on the "tool_hash" field.
func ToolHashNEQ(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNEQ(FieldToolHash, v))
}

// ToolHashIn applies the In predicate on the "tool_hash" field.
func ToolHashIn(vs ...string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldIn(FieldToolHash, vs...))
}

// ToolHashNotIn applies the NotIn predicate on the "tool_hash" field.
func ToolHashNotIn(vs ...string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNotIn(FieldToolHash, vs...))
}

// ToolHashGT applies the GT predicate on the "tool_hash" field.
func ToolHashGT(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGT(FieldToolHash, v))
}

// ToolHashGTE applies the GTE predicate on the "tool_hash" field.
func ToolHashGTE(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGTE(FieldToolHash, v))
}

// ToolHashLT applies the LT predicate on the "tool_hash" field.
func ToolHashLT(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLT(FieldToolHash, v))
}

// ToolHashLTE applies the LTE predicate on the "tool_hash" field.
func ToolHashLTE(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLTE(FieldToolHash, v))
}

// ToolHashContains applies the Contains predicate on the "tool_hash" field.
func ToolHashContains(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldContains(FieldToolHash, v))
}

// ToolHashHasPrefix applies the HasPrefix predicate on the "tool_hash" field.
func ToolHashHasPrefix(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldHasPrefix(FieldToolHash, v))
}

// ToolHashHasSuffix applies the HasSuffix predicate on the "tool_hash" field.
func ToolHashHasSuffix(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldHasSuffix(FieldToolHash, v))
}

// ToolHashEqualFold applies the EqualFold predicate on the "tool_hash" field.
func ToolHashEqualFold(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEqualFold(FieldToolHash, v))
}

// ToolHashContainsFold applies the ContainsFold predicate on the "tool_hash" field.
func ToolHashContainsFold(v string) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldContainsFold(FieldToolHash, v))
}

// ToolCountEQ applies the EQ predicate on the "tool_count" field.
func ToolCountEQ(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldToolCount, v))
}

// ToolCountNEQ applies the NEQ predicate on the "tool_count" field.
func ToolCountNEQ(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNEQ(FieldToolCount, v))
}

// ToolCountIn applies the In predicate on the "tool_count" field.
func ToolCountIn(vs ...int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldIn(FieldToolCount, vs...))
}

// ToolCountNotIn applies the NotIn predicate on the "tool_count" field.
func ToolCountNotIn(vs ...int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNotIn(FieldToolCount, vs...))
}

// ToolCountGT applies the GT predicate on the "tool_count" field.
func ToolCountGT(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGT(FieldToolCount, v))
}

// ToolCountGTE applies the GTE predicate on the "tool_count" field.
func ToolCountGTE(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGTE(FieldToolCount, v))
}

// ToolCountLT applies the LT predicate on the "tool_count" field.
func ToolCountLT(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLT(FieldToolCount, v))
}

// ToolCountLTE applies the LTE predicate on the "tool_count" field.
func ToolCountLTE(v int) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLTE(FieldToolCount, v))
}

// ToolsChangedEQ applies the EQ predicate on the "tools_changed" field.
func ToolsChangedEQ(v bool) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldToolsChanged, v))
}

// ToolsChangedNEQ applies the NEQ predicate on the "tools_changed" field.
func ToolsChangedNEQ(v bool) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNEQ(FieldToolsChanged, v))
}

// ToolsChangedSessionEQ applies the EQ predicate on the "tools_changed_session" field.
func ToolsChangedSessionEQ(v bool) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldToolsChangedSession, v))
}

// ToolsChangedSessionNEQ applies the NEQ predicate on the "tools_changed_session" field.
func ToolsChangedSessionNEQ(v bool) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNEQ(FieldToolsChangedSession, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.FieldLTE(FieldCreatedAt, v))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.Session) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CacheDiagnostic) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CacheDiagnostic) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CacheDiagnostic) predicate.CacheDiagnostic {
	return predicate.CacheDiagnostic(sql.NotPredicates(p))
}
